### PR TITLE
Introduce run.sh for container fix #6417

### LINKED ISSUE #6417: introduce run.sh for TW and Publisher and make runContainer.sh use it (check what Puppet does)
from: https://github.com/dmwm/CRABServer/issues/6416

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
@ddaina in a way this is still work in progress, need to complete the cleanup of all env/start/run scripts, merge, tag, rebuild with new tag, test, and fix issues. Feel free to have a peek and comment but no worries

**Comment by ddaina** [comment]
I'll have a look. By any chance you have docker image in your DH account with changes in this PR?

**Comment by belforte** [comment]
yes, here's the image: sbelforte/crabtaskworker:v3.210218-GH 
I reused the -GH suffix from when testing adding GH repos, But latest one has also new run.sh

**Comment by belforte** [comment]
I tested with  `./runContainer.sh -r sbelforte  -v v3.210218-GH -s TaskWorker` on crab-dev-tw01, so if you log there it is already downloaded. I am not running on it anymore for a while.

**Review by ddaina — COMMENTED** [review]
thanks @belforte I had a look into it, my only comment is what you wrote yourself here:
https://github.com/dmwm/CRABServer/issues/6417#issuecomment-786518168 

> but I verified that the symlinks are created by run.sh

i.e. we should update how links are created because currently assumption is made that it happens from /data/srv/TaskManager directory

**Comment by ddaina** [comment]
> i.e. we should update how links are created because currently assumption is made that it happens from /data/srv/TaskManager directory

yeah, I think I am wrong and it should stay as is.

**Comment by belforte** [comment]
i Thought I replied to comment by mail. But it looks it did not work. Here's again:

links are created already in the correct place:
```
[crab3@crab-dev-tw01 ~]$ docker logs TaskWorker
run.sh is RUNNING in directory /data/srv/TaskManager
check link logs ....
lrwxrwxrwx. 1 crab3 crab3 30 Feb 26 10:15 logs -> /data/hostdisk/TaskWorker/logs
check link current/TaskWorkerConfig.py ....
lrwxrwxrwx. 1 crab3 crab3 49 Feb 26 10:15 current/TaskWorkerConfig.py -> /data/hostdisk/TaskWorker/cfg/TaskWorkerConfig.py
check link nohup.out ....
lrwxrwxrwx. 1 crab3 crab3 35 Feb 26 10:15 nohup.out -> /data/hostdisk/TaskWorker/nohup.out
nohup: appending output to 'nohup.out'
[crab3@crab-dev-tw01 ~]$ 
```

**Comment by ddaina** [comment]
yes, you are right. all good then, we should merge.

**Pull request merged**
