### PR TITLE
pipe crablog to stdout

### PR DESCRIPTION
**Pull request by novicecpp**
Fix https://github.com/dmwm/CRABServer/issues/7463#issuecomment-1341570409 on CRAB REST's side.

Make `crablog` to write to stdout when `data.loggingFile` in [config.py](https://gitlab.cern.ch/crab3/crab-secrets/-/blob/master/kubernetes/sample/crabserver/config.py) is `None`.
I added the suffix log type `Type=crablog` and `Type=cherrypylog` to all log messages inside the code to make it more easy to parse in the log pipeline or grep in vocms0750.

Note that `crablog` is a separate logger from cherrypy that we use it in CRAB REST code.

~~The diff files in `cicd/logs_stdout` is what we need to change later in it original repository. But, we need to test it first (in testbed) if it work properly.~~ Move to https://gitlab.cern.ch/tseethon/logstdout/-/tree/master/CRABServer/cicd/logs_stdout

### CODE REVIEW

**Review by belforte — APPROVED** [review]
I do not rully understand all lines, but I like this and it looks good. It may be nice eventually to have a bit more of comments to help people like me to understand "years from now"

**Comment by belforte** [comment]
very nice, thanks

**Comment by novicecpp** [comment]
Thanks Stefano. I will not merge this PR until we get approval from CMSWEB team.

**Comment by belforte** [comment]
Hi @novicecpp can this be merged now ? I'd like to make a new tag to do a proper test to changes in REST and TW so far, including the new recipe for UI build (still to be merge by Imran, though https://github.com/dmwm/CMSKubernetes/pull/1311#issuecomment-1419132299 )

**Comment by novicecpp** [comment]
Yes. I also bump wmcver to `2.1.7rc3`.

**Pull request merged**
