### PR TITLE
Make dashboard data compatible with InfluxDB

### PR DESCRIPTION
**Pull request by lecriste**
https://github.com/dmwm/CRABServer/issues/5855?email_source=notifications&email_token=ABGU5BBAZTFU2AESB4ESG33RCJ37HA5CNFSM4HBYVRLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELL4G4A#issuecomment-584565616

### CODE REVIEW

**Comment by belforte** [comment]
can you explain a bit what this does ?
AFAICT it add structures to a jsonDoc whicg is then sent to http://monit-metrics:10012/
but I though that it was decided not to send the influxdb stuff.

As a different note, I am confused by
https://github.com/dmwm/CRABServer/blob/61b725e88a88419cc786c962eaa3f868a725a106/src/script/Monitor/GenerateMONIT.py#L265
which seems to try to make a list of out a dictionary.  AFAICT that `jsonDoc` is used as `document` in
https://github.com/dmwm/CRABServer/blob/61b725e88a88419cc786c962eaa3f868a725a106/src/script/Monitor/GenerateMONIT.py#L29
and since `jsonDumps` takes a string as input, I am confused as to what it means to pass a list, or even a dictionary.

**Comment by lecriste** [comment]
> can you explain a bit what this does ?
> AFAICT it add structures to a jsonDoc whicg is then sent to http://monit-metrics:10012/

Right, that's all about it.

> but I though that it was decided not to send the influxdb stuff.

Yes. If at some point we decide to send to InfluxDB, these additional tags and fields structures are required according to [this documentation](https://monitdocs.web.cern.ch/monitdocs/ingestion/service_metrics.html#writing-to-influxdb).
For the moment it does not make any difference.

> As a different note, I am confused by
> 
> https://github.com/dmwm/CRABServer/blob/61b725e88a88419cc786c962eaa3f868a725a106/src/script/Monitor/GenerateMONIT.py#L265
> 
> 
> which seems to try to make a list of out a dictionary. AFAICT that `jsonDoc` is used as `document` in
> https://github.com/dmwm/CRABServer/blob/61b725e88a88419cc786c962eaa3f868a725a106/src/script/Monitor/GenerateMONIT.py#L29
> 
> 
> and since `jsonDumps` takes a string as input, I am confused as to what it means to pass a list, or even a dictionary.

No idea, I did not touch that part of the code.

**Comment by belforte** [comment]
I will review the file to make sure that comments in the code explain things satisfactorely (at least for me) and merge this.

**Comment by belforte** [comment]
too much trouble to edit @lecriste branch. I will merge and add comments later

**Comment by belforte** [comment]
comments added in
https://github.com/dmwm/CRABServer/pull/6022

**Pull request merged**
