### PR TITLE
Resolve #5846

### LINKED ISSUE #5846: port to WMCore 1.2.0
there is some non-backward compatible change e.g. in scram(), see:
https://github.com/dmwm/WMCore/pull/8989
and
https://github.com/dmwm/WMCore/issues/9113

### PR DESCRIPTION
**Pull request by lecriste**
https://github.com/dmwm/WMCore/issues/9113

### CODE REVIEW

**Comment by belforte** [comment]
can you please explain better what you are doing here ?
" Remove indispensable calls to previous logName files"  tells very little to me.
(maybe you meant non-indispensable i.e. not absolutely needed ?) yet those lines could have been there for some reason.
I really do not understand why we need to change this kind of things for new WMCore, AFAIK it is simply a matter of providing proper logger to the scram module and if we can't for some reason, nail it down and talk with Alan about a new signature for scram()

**Comment by lecriste** [comment]
> can you please explain better what you are doing here ?
> " Remove indispensable calls to previous logName files" tells very little to me.
> (maybe you meant non-indispensable i.e. not absolutely needed ?) yet those lines could have been there for some reason.

I am just following @amaltaro instruction to perform a test, no intention to merge this code.
I removed the lines that were making jobs failing (i.e. "indispensable" for the job to run) after the removal of the dedicated scram log file creation.

> I really do not understand why we need to change this kind of things for new WMCore, AFAIK it is simply a matter of providing proper logger to the scram module and if we can't for some reason, nail it down and talk with Alan about a new signature for scram()

Fully agree, this is just a test.

**Comment by belforte** [comment]
I'd rather have the log back !

**Comment by amaltaro** [comment]
This is what I pointed to Leonardo:
https://github.com/dmwm/WMCore/pull/8989/files#diff-85b29c8c30f3655de9dbe5babde80139R328

so both the stdout and stderr should be going to the logger (or root logger) defined by the CRAB runtime code.
IF those lines/logs can't be seen anywhere in any possible log files within the worker node sandbox, then we have a problem and I better change WMCore to keep accepting that log file name once again.

Please do let me know and apologies for the extra work.

**Comment by lecriste** [comment]
I see that "Subprocess stdout was" string:
https://cmsweb-testbed.cern.ch/scheddmon/0195/cms382/190411_135159:lecriste_crab_AutomaticSplitting_data_preprod_transferLogsTrue_3-3-1905-rc2_afterDisaster/job_out.0-1.0.txt

and then jobs failed as expected because of this exception:
https://github.com/lecriste/CRABServer/blob/update-to-WMCore/scripts/CMSRunAnalysis.py#L798
triggered by the missing `edmProvDumpOutput.log` file that used to be created with the `logName` parameter:
https://github.com/dmwm/CRABServer/pull/5862/commits/4d2124a8181233cbe7b84f5438a317cfd14c1395#diff-b4df3d7055437f8d2eeafa0b449218d5L571

With the current code we must find how to replace, AFAICT, the lines removed here: 
https://github.com/dmwm/CRABServer/pull/5862/commits/f1ccce36947dcf24d863c5c0bdc18d295489853e

and this one:
https://github.com/lecriste/CRABServer/blob/update-to-WMCore/scripts/CMSRunAnalysis.py#L773

@amaltaro any hint?

**Pull request closed without merging**
