### PR TITLE
allow tm_rest_(host|uri) values to be missing

### PR DESCRIPTION
**Pull request by belforte**
consolidates in Create.py and updateOracle.sql changes already done in DB

### CODE REVIEW

**Comment by belforte** [comment]
@mapellidario this should be very harmless, but please  add your pair of eyes

**Comment by novicecpp** [comment]
Did you forget to commit the latest change?

**Comment by belforte** [comment]
thanks Wa. Yes, I did something wrong. Will review

**Comment by belforte** [comment]
everything was put already in master for what concerns "allow tm_rest_(host|uri) values to be missing". This PR is totally uses since only adds an extra blank line by mistakes.
Sorry for the noise. I somehow got confused when checking my local branches.

**Pull request closed without merging**
