### PR TITLE
force using IPV4 address for s3.cern.ch ref #7268

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Review by novicecpp — APPROVED** [review]
LGTM

**Comment by belforte** [comment]
I am currently running this change in production pod crabserver-567d5ccc97-7nqdc with no issues (and no TimeOut).
But am not sure if we want to merge and deploy including the (small) changes to REST (IIUC #7254 and #7256 ) which are now in master, or do a path on top of v3.220513 which we run now.

**Comment by novicecpp** [comment]
It shoud be fine. Yesterday I rebase https://github.com/dmwm/CRABServer/pull/7255 to those change and run test in preprod https://github.com/dmwm/CRABServer/issues/7269, it work fine. All test passed.

Here some logs output from MeasureTime
Screenshot from 2022-05-26 12-29-48

**Comment by belforte** [comment]
OK. Let's merge, tag, build and  deploy. So we decouple our ops from the K8s IPV6 debugging.

**Pull request merged**
