### PR TITLE
Add check to delete stale lock file (fix #6182)

### LINKED ISSUE #6182: WMArchiveUploader should detect and remove stale lock files
see e.g.
```
Logbook             : Analysis Operations
Author              : prajesh sharma
Email               : mailto:prajesh.sharma@cern.ch
Category            : Fix
Shifter Role        : AnalysisOps Expert
Subject             : WMArchiveUploader service showing puppet error

Logbook URL         : https://cms-logbook.cern.ch/elog/Analysis+Operations/3225

=================================

WMArchiveUploader service not started and showing errors during puppet run.[1]
I remove following file, now it is working.

[root@vocms0155 ~]# rm /data/srv/WMArchiveWD/WMArchiveUploader.lock
```

### PR DESCRIPTION
**Pull request by ddaina**

### CODE REVIEW

**Review by belforte — CHANGES_REQUESTED** [review]
please change function name delpid to removePidfile
I would have done myself but suspect that you did not enable edit by maintainers in the PR. If you did, I have not found the proper button :-(
also fix major pylint warnings W0702 and W1201

**Review by belforte — APPROVED** [review]

**Comment by belforte** [comment]
Looks fine @ddaina  Please fix major pylint complains and merge

**Comment by ddaina** [comment]
I fixed major pylint warnings except the one on 
`W0231, line 170 in WMArchiveUploader.__init__: __init__ method from base class 'Daemon' is not called ` 
which is called in `def loadConf(self)` after reading config file.

**Comment by belforte** [comment]
I'd rather not touche the "daemonization code", suggest to silence it via #pylint disable

> I fixed major pylint warnings except the one on
> `W0231, line 170 in WMArchiveUploader.__init__: __init__ method from base class 'Daemon' is not called `
> which is called in `def loadConf(self)` after reading config file.

**Pull request merged**
