### PR TITLE
make tm_rest_host and tm_rest_uri optional

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
very safe (and tested), anyhow, Dario please have a critical look

**Comment by belforte** [comment]
only affects CRAB REST

**Review by mapellidario — APPROVED** [review]
The changes look good, nothing strange. 
However i miss the context of these changes. Are they connected to any issue? is this the followup of a past cleanup?

**Comment by belforte** [comment]
it is indeed a cleanup associated to, but not strictly needed for, #7480

**Pull request merged**
