### PR TITLE
Convert 'ids' list of intergers to list of strings before passing it to join.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**

### CODE REVIEW

**Comment by ericvaandering** [comment]
So in WMCore we're trying to be really good about at least cleaning up unused arguments and imports. You really should not be re-defining built-ins either.

**Comment by AndresTanasijczuk** [comment]
What is the problem with using the built-in function map (line 180)?

**Comment by ericvaandering** [comment]
http://pylint-messages.wikidot.com/messages:w0141

**Comment by ericvaandering** [comment]
In other words, I think ", ".join(ids) works just fine.

**Comment by AndresTanasijczuk** [comment]
", ".join(\<list of integers\>) doesn't work. I get the same error this user got: https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/971/1/1/1.html

**Comment by annawoodard** [comment]
It just wants a list comprehension, I think:
```
>>>", ".join([str(x) for x in [1, 2, 3]])
'1, 2, 3'
```

**Comment by ericvaandering** [comment]
That will work for sure. I figured the join function would do it's own str() since it is a member function of string. :-)

**Comment by belforte** [comment]
can we now get cavalier about implicit type casting ?
Last book I read (log ago, and was C++ !) was very strong about
being careful there.

**Comment by ericvaandering** [comment]
duck-typing is the base design of OO in python. But Anna's example is explicit casting.

**Comment by ericvaandering** [comment]
test this please

**Comment by belforte** [comment]
anyhow if the problem is
https://github.com/AndresTanasijczuk/CRABServer/blob/killjobids/src/python/TaskWorker/Actions/DagmanKiller.py#L180
you could simply give to `print` a list and let it transform it into strings.

what is the argument to this `killJobs(self,ids)` , i.e. `ids`, supposed to be ?
A list, an ntuple, ... ?

**Comment by ericvaandering** [comment]
```msg  = "The CRAB server backend was not able to kill these jobs (%s)," % ids```

would give something almost as readable. It would say `jobs([1, 2, 3])` instead of `jobs(1, 2, 3)`.

Also note outer parentheses after % are not strictly necessary since there is only one value being formatted.

**Comment by belforte** [comment]
remove () around %s and gets perfectly readable

**Comment by ericvaandering** [comment]
"what is the argument to this `killJobs(self,ids)` , i.e. `ids`, supposed to be ?
A list, an ntuple, ... ?"

It doesn't matter. :-) As long as everything the function tries to do to ids works, it's all good. Could be list or tuple (they are almost the same) or an instance of AndresStructure.

**Comment by belforte** [comment]
cool. I learnt something new :-)
In duck-typing spirit print(ids) is the best. otherwise killJob need to be
prepared for any kind of argument and hand it properly.

On 09/29/2015 10:16 PM, Eric Vaandering wrote:
> duck-typing is the base design of OO in python. But Anna's example is explicit casting.
>
Indeed what you wrote later seems to be the essence of duck-typing
> It doesn't matter. :-) As long as everything the function tries to do to ids works, it's all good. Could be list or tuple (they are almost the same) or an instance of AndresStructure.

the "as long as everything works" is what bothers me a bit..

**Comment by AndresTanasijczuk** [comment]
Changed to "... these jobs %s," % (ids)

**Comment by ericvaandering** [comment]
Sort of. All Anna's suggestion assumes is that ids is iterable and can be converted to a string. Yours is even simpler and just assumes it can be converted to a string. 

Andres, even though Jenkins is no longer firing on pylint since you no longer are making the code worse, you should consider another commit that just cleans up a lot of the super-easy stuff it pointed out. What we are doing in WMCore land is a 2nd commit, not a rebase such that you separate out real changes from trivial stuff.

**Comment by AndresTanasijczuk** [comment]
Ok, will keep that in mind for next time.

**Comment by belforte** [comment]
I was talking in abstract, surely not complaining nor worried about Anna's code.
I have seen enough cases in Crab2 where implicit type conversion was causing problems...
gee.. I promise I stop here.

**Pull request merged**
