### PR TITLE
adapt FindFaileMigration to post-transition-to-Go

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
@mapellidario please review, possibly test (I did.. but.. one never knows) and merge with changes for new CSV file format before tagging and deploying. No need for FindAndDeleteMigrations.. which anyhow would be just a matter of changing a couple lines here

**Review by mapellidario — APPROVED** [review]
I tested it on testbed and it looks good.

the only change for adapting to the new CSV format would be 

```diff
-         blocks.add(items[2])
+         blocks.add(items[3])
```

I suggest that we merge this PR, i rebase #7380 on master branch, then I apply there the aforementioned change, merge #7380 and create a new release

**Comment by belforte** [comment]
well a better change for new format would be to use reqId from CSV file directly (as it was in the original version) w/o looking it up from the block name. But there's still time for that. feel free to open a GH and assign to me

**Comment by belforte** [comment]
P.S. you can run it on production Publisher, I have done it already !

**Comment by belforte** [comment]
from my side, ready to merge.

**Pull request merged**
