### PR TITLE
Introduce LFN2PFN from RUCIO

### PR DESCRIPTION
**Pull request by dciangot**
Depends on WMCORE PR: https://github.com/dmwm/WMCore/pull/9977

Tested on dev instance for both Rucio and FTS transfer mode.

How do we proceed with this @belforte ?

### CODE REVIEW

**Comment by belforte** [comment]
what is exactly the question ? IIUC we need to get a new WMCore tag with https://github.com/dmwm/WMCore/pull/9977 and then can test this in preprod

**Comment by dciangot** [comment]
TODO: The only place to implement a cache are transfer scripts. It needs to be implemented both on FTS and RUCIO transfer script

**Comment by belforte** [comment]
@dciangot please remove REST files from this PR. See https://github.com/dmwm/CRABServer/issues/6102#issuecomment-715562364

**Comment by belforte** [comment]
this is now done partly with different code, partly picking files from here and inserting via a different PR.
References:
https://github.com/dmwm/CRABServer/pull/6211 https://github.com/dmwm/CRABServer/pull/6219 https://github.com/dmwm/CRABServer/pull/6221 https://github.com/dmwm/CRABServer/pull/6222

**Pull request closed without merging**
