### PR TITLE
Query collector in Authentificated subprocess

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by juztas** [comment]
@mmascher @bbockelm

**Comment by bbockelm** [comment]
You'll want to look at the other uses of the authenticated sub-process class.  The code inside the "with" block will be executed in a sub-process, meaning you must communicate it back to the parent by writing into the pipe.

**Comment by juztas** [comment]
@mmascher leave it open

**Comment by ericvaandering** [comment]
retest this please

**Pull request closed without merging**
