### PR TITLE
Propagate errors in cmscp and postjob to the JSON job report file.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**
This pull is to solve the issue that the error summary in the crab status output shows things like "N jobs have failed in exit code 0" and message "OK" for failures in stageout. Here I write all errors in cmscp and postjob in the job report so that the error summary can read these errors. For errors in the post-job I put exit code = 99999 in the error summary file. I still need to make a pull in the client so that this exit code is interpreted as "error in post-processing step".
I also used a new exit code 80001 for failure in (log) file metadata upload in cmscp, but since this failure is not propagated to the job report because the upload of the file metadata is retried in the postjob, this exit code will not be observed anywhere. For the moment is just an internal exit code used in cmscp.

### CODE REVIEW

**Comment by belforte** [comment]
hi @AndresTanasijczuk does this then obsolete the question you had in #4589 ?

**Comment by AndresTanasijczuk** [comment]
To @belforte 
Yes, I use exit code 80001 for file metadata upload failures.

**Comment by AndresTanasijczuk** [comment]
@mmascher Consider first merging #4764 then I will rebase this pull.

**Comment by mmascher** [comment]
You can rebase, I merged th other pull

**Comment by AndresTanasijczuk** [comment]
Rebased.

**Comment by mmascher** [comment]
What I do not like about this pull is that it is loading/diumping the jobreport.json many times in the postjob. If that's acceptable in the jobwrapper, I feel unconfortable in doing it in the postjob as all the postjob run on the same machine. I am probably just being paranoid, but if there was a way to save and load the jobreport.json only once I would prefer. Look for me later.

**Comment by mmascher** [comment]
Andres will open a ticket to optimize this. For the moment merging as this is critical to propagate errors to the error summary.

**Pull request merged**
