### PR TITLE
Implement resubmission of publications. Also fixes #5070.

### LINKED ISSUE #5070: When resubmitting tasks in SUBMITFAILED, either ignore or give error message if --jobids is specified
For a task in SUBMITFAILED status there were no jobs created, so the --jobids option makes no sense. If one specifies it, one currently gets an error message like this:

```
$ crab resubmit --jobids=1
...
The server answered with an error.
Server answered with: Execution error
Reason is: CRAB3 server refused to resubmit the following jobs: [1]. Only jobs in status ['failed'] can be resubmitted. Jobs in status ['finished'] can also be resubmitted, but only if the jobid is specified ...
```

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**
This is resubmission via the 'crab resubmit' command. 
I tested this PR using ASO/Couch in testbed and it worked as I expected, but I would like @HassenRiahi to check the query of the view that I do in DagmanResubmitter, because I tried first using the same query as in the retry-publish script
```
failedPublications = database.loadView('DBSPublisher','PublicationFailedByWorkflow',{'reduce':False,'key':taskname})['rows']
```
but it didn't work; it returned an empty list. So I changed to
```
failedPublications = database.loadView('DBSPublisher', 'PublicationFailedByWorkflow', {'reduce': False})['rows']
```

### CODE REVIEW

**Comment by belforte** [comment]
@dciangot Diego, can you have a look ? I think it is due time that you take more charge about ASO

**Comment by dciangot** [comment]
@belforte yes, ok. Just to clarify, the question here still about the correct sintax to query the view, right?
If yes, I think that the correct way to do that is:

failedPublications = database.loadView('DBSPublisher','PublicationFailedByWorkflow',{'reduce':False,'startkey':[taskname],'endkey':[taskname, {}]})['rows']

**Comment by AndresTanasijczuk** [comment]
Thanks @dciangot That's what I needed to know. I will try it.

**Comment by AndresTanasijczuk** [comment]
Tested with the suggested way to query the view by Diego and works ok.

**Comment by belforte** [comment]
with respect to discussion in the CRAB meeting yesterday, yes I can merge, but I can't review or validate in any way by tonight. @mmascher what's the usual way of doing things  ? Merge and cross fingers, or review first ?

**Comment by mmascher** [comment]
I have done merge and cross finger with a precise person like @AndresTanasijczuk that says he tested it if I had no time. But I usually review.

**Pull request merged**
