### PR TITLE
getProxiedWebDir takes server as arg. Fix #6360

### LINKED ISSUE #6360: avoid creating a new server in getProxiedWebDir
it is used in CRABClient and in Schedd by AdjustSites.
should try to use  rest instance created outside so that proper userAgent, port and version can be reported.

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
I have tested this on stefanovm so far. But since there are changes to AdustSites.py which affects starting of any tasks, we need to test a bit more before putting in production.

**Review by ddaina — APPROVED** [review]
looks good

**Comment by ddaina** [comment]
messages crossed. anyway, will have in mind regarding the testing once it is in preprod.

**Comment by belforte** [comment]
thanks. I have another small change for CRABserver in  mind still in this "userAgent" area. 
I'd like to improve this list. Version number 0.0.0 should all be from old code running on schedd's and will take a month to go away, but still.. too many lines, and CRABServer is a catchall which I'd like to get rid of.
Screenshot from 2021-01-26 09-55-37

**Pull request merged**
