### PR TITLE
Some refactoring of the postjob in view of the rewriting we will need for the defer

### PR DESCRIPTION
**Pull request by mmascher**
More will probably come

### CODE REVIEW

**Comment by mmascher** [comment]
Also, not sure if I should squash these commits or what, they seems pretty in order so I would like to keep them as they are. Opinions?

**Comment by mmascher** [comment]
There is one more thing I would like to change but for the moment these are ready to go. Maybe @AndresTanasijczuk can review this pull?

@juztas , I know you have to change some things in the postjob, up to you if you want to start and rebase or you want to wait for this to be merged. I do not expect too many comments from Andres.

**Comment by juztas** [comment]
PostJob not so much. More on RetryJob,  I am fine with rebase ;)

**Comment by AndresTanasijczuk** [comment]
All looks good for me.

**Comment by mmascher** [comment]
@juztas @AndresTanasijczuk 

Can you have a look at this (in particular the last commit, the other are just refactoring)?

**Comment by juztas** [comment]
Just my comment, what I would change:
Why not .format everywhere?
Why in execute_interval you are trying to read job_ad file from PER_JOB_HISTORY_DIR, while if this is DEFERRED job, might be that file does not exist anymore? If it is deferred postjob, this file is copied to spool directory and might not exist at PER_JOB_HISTORY_DIR, of course might have cases where it failed to get job_ad file in first, second, N try...
Why so much ose.errno != 17, Isn`t there a nicer way to do that?

My view:
Start PostJob, if First time, prepare directory structure and all needed files, symlinks, check classads, REPORT, see how transfers are going and if stuck, write all variables and needed info to a file and  DEFER.
DEFER time ....
Start PostJob, you see it`s not first time, load previous saved data, see how file transfers going on, stuck - DEFER, finished - upload filemetadata, report to dashboard, DONE. failed - print env and classads, report to dashboard and exit properly checking if it is retryable or not.

**Comment by mmascher** [comment]
Hi Justas,

On Thu, Jul 23, 2015 at 11:38 PM, Justas Balčas <notifications@github.com>
wrote:

> Just my comment, what I would change:
> Why not .format everywhere?
>

ok, I will "normalize" the code.


> Why in execute_interval you are trying to read job_ad file from
> PER_JOB_HISTORY_DIR, while if this is DEFERRED job, might be that file does
> not exist anymore? If it is deferred postjob, this file is copied to spool
> directory and might not exist at PER_JOB_HISTORY_DIR, of course might have
> cases where it failed to get job_ad file in first, second, N try...
>

Uhm, it seemed the jobad was always there:

http://vocms059.cern.ch/mon/cms1925/150722_142447:mmascher_crab_test_pj_bigunitsmmascher-dev6_3/postjob.1.0.txt

Anyhow, I am loading every time because there are things that are checked
every loop. Not sure I can move the loading of the jobad but I'll check
this out.

Why so much ose.errno != 17, Isn`t there a nicer way to do that?
>

I guess that depends on people taste, that's the nicer way to do that in my
opinion, and in general the pythonic way of doing thigs.


> My view:
> Start PostJob, if First time, prepare directory structure and all needed
> files, symlinks, check classads, REPORT, see how transfers are going and if
> stuck, write all variables and needed info to a file and DEFER.
> DEFER time ....
> Start PostJob, you see it`s not first time, load previous saved data, see
> how file transfers going on, stuck - DEFER, finished - upload filemetadata,
> report to dashboard, DONE. failed - print env and classads, report to
> dashboard and exit properly checking if it is retryable or not.
>

yeah, that's what I am doing :)

**Comment by belforte** [comment]
let's not base code on "did not happen yet". You know better then this !

**Comment by juztas** [comment]
if you have job_ad in finished_jobs, you do not need to find out this from PER_JOB_HISTORY_DIR and we might anytime increase cleanup script. With all these small jobs it is filling up really fast.

Marco, if you doing that, why not to have two separated functions for that (first_time, second_time)? Just a thought :) Maybe it`s my taste, what I think is cleaner ;)

**Comment by belforte** [comment]
On 07/24/2015 09:59 AM, Justas Balčas wrote:
> we might anytime increase cleanup script.

again.. let's not confuse it did not happen by accident with
it cannot happen by design. CRAB3 is complex and intricated
enough that it better be rock solid for any hope of long term
mind sanity. THere are already too many things that depend on
things done elsewhere and dependencies are not clearly documented anywhere.

**Comment by AndresTanasijczuk** [comment]
Pull is Ok FMPOV. I think I would have done the same as you.

**Pull request merged**
