### PR TITLE
Simplify code for cutting lines

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by belforte** [comment]
I would have simply replaced `print line` with `print line(:1024)` (sort of to convey the spirit)

**Comment by mmascher** [comment]
I like that we print `NOTICE: Some lines have been truncated, because it was bigger than %s characters.` at the end of the CMSSW output, that's why I kept the function. But I tried to simplify the logic

**Comment by belforte** [comment]
I know, and I see the nicety of it as well. But after thinking about it, I decided I like it more
to print all of the times : here's CMSSW output truncated to 1024 char's per line.
Sort of part of the general rule "jobs run in a box", there are limits all around you, be aware.

**Comment by mmascher** [comment]
So something like this? (I am using an auxiliary function to make my life simpler)

**Comment by belforte** [comment]
yes, something like that

**Pull request merged**
