### PR TITLE
remove Pre-python 2.6 constructs. fix #5553

### LINKED ISSUE #5553: fix python3 compatibility issues
as per
https://cmssdt.cern.ch/jenkins/view/All/job/DMWM-CRABServer-PR-Test/8/artifact/artifacts/PullRequestReport.html#pyfuture
pasted below as I am not sure of persistence of above link
```

Unit test summary

    No changes to unit tests

Summary of pylint report

Warnings from pylint by file and severity

Warnings from pycodestyle (pep8) by file

Summary of python3 compatibility report
Imports for Python3 compatability missing in new files. Please fix this:

    New file src/python/CRABInterface/DataCampaign.py does not use python 3 division. Please add `from __future__ import division`.
    New file src/python/CRABInterface/RESTCampaign.py does not use python 3 division. Please add `from __future__ import division`.
    New file src/python/TaskWorker/Actions/Final.py does not use python 3 division. Please add `from __future__ import division`.
    New file src/python/TaskWorker/Actions/Recurring/GenerateXMLForTW.py does not use python 3 division. Please add `from __future__ import division`.

Pre-python 2.6 constructs are introduced by this pull request. This must be fixed. Suggested patch follows:

--- ./setup.py	(original)
+++ ./setup.py	(refactored)
@@ -2,6 +2,7 @@
 """
     NOTE: This is intended to run automagically. Keep the deps minimal
 """
+from __future__ import print_function
 import sys
 import os
 import os.path
@@ -151,7 +152,7 @@
 
     def finalize_options(self):
         if self.system not in systems:
-            print "System %s unrecognised, please use '-s CRABInterface'" % self.system
+            print("System %s unrecognised, please use '-s CRABInterface'" % self.system)
             sys.exit(1)
 
         # Expand various sources and maybe do the c++ build.
@@ -197,10 +198,10 @@
     def finalize_options(self):
         # Check options.
         if self.system not in systems:
-            print "System %s unrecognised, please use '-s CRABInterface'" % self.system
+            print("System %s unrecognised, please use '-s CRABInterface'" % self.system)
             sys.exit(1)
         if self.patch and not os.path.isdir("%s/xbin" % self.prefix):
-            print "Patch destination %s does not look like a valid location." % self.prefix
+            print("Patch destination %s does not look like a valid location." % self.prefix)
             sys.exit(1)
 
         # Expand various sources, but don't build anything from c++ now.
--- ./bin/ftscp.py	(original)
+++ ./bin/ftscp.py	(refactored)
@@ -1,5 +1,6 @@
 #!/usr/bin/python
 
+from __future__ import print_function
 import re
 import sys
 import time
@@ -34,22 +35,22 @@
     def cancel(self):
         if self._id:
             cmd = "glite-transfer-cancel -s %s %s" % (fts_server, self._id)
-            print "+", cmd
+            print("+", cmd)
             os.system(cmd)
 
     def submit(self):
         cmd = "glite-transfer-submit -s %s %s %s" % (fts_server, self._source, self._dest)
-        print "+", cmd
+        print("+", cmd)
         status, output = commands.getstatusoutput(cmd)
         if status:
             raise Exception("glite-transfer-submit exited with status %s.\n%s" % (status, output))
         output = output.strip()
-        print "Resulting transfer ID: %s" % output
+        print("Resulting transfer ID: %s" % output)
         return output
 
     def status(self):
         cmd = "glite-transfer-status -s %s %s" % (fts_server, self._id)
-        print "+", cmd
+        print("+", cmd)
         status, output = commands.getstatusoutput(cmd)
         if status:
             raise Exception("glite-transfer-status exited with status %s.\n%s" % (status, output))
@@ -64,7 +65,7 @@
             idx += 1
             time.sleep(self._sleep)
             status = self.status()
-            print status
+            print(status)
 
             if status in ['Submitted', 'Pending', 'Ready', 'Active', 'Canceling', 'Hold']:
                 continue
@@ -88,12 +89,12 @@
 
 def main():
     if len(sys.argv) != 3:
-        print "Usage: ftscp  "
-        print "\nSource and destination should be of the format $SITE:$LFN"
+        print("Usage: ftscp  ")
+        print("\nSource and destination should be of the format $SITE:$LFN")
         sys.exit(1)
 
     source, dest = resolvePFNs(sys.argv[1], sys.argv[2])
-    print "Copying %s to %s" % (source, dest)
+    print("Copying %s to %s" % (source, dest))
 
     global g_Job
     g_Job = FTSJob(source, dest)
--- ./bin/logon_myproxy_openssl.py	(original)
+++ ./bin/logon_myproxy_openssl.py	(refactored)
@@ -1,10 +1,11 @@
+from __future__ import print_function
 import logging, sys
 from hashlib import sha1
 from WMCore.Credential.SimpleMyProxy import SimpleMyProxy
 
 if len(sys.argv) is not 5:
-    print "Usage example: "
-    print 'python logon_openssl.py "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mcinquil/CN=660800/CN=Mattia Cinquilli" /data/certs/hostkey.pem /data/certs/hostcert.pem "/DC=ch/DC=cern/OU=computers/CN=mattia-dev01.cern.ch"'
+    print("Usage example: ")
+    print('python logon_openssl.py "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mcinquil/CN=660800/CN=Mattia Cinquilli" /data/certs/hostkey.pem /data/certs/hostcert.pem "/DC=ch/DC=cern/OU=computers/CN=mattia-dev01.cern.ch"')
     sys.exit(1)
 
 logger = logging.getLogger("OpenSSL MyProxy test")
@@ -18,4 +19,4 @@
 timeleftthreshold = 60 * 60 * 24
 mypclient = SimpleMyProxy(defaultDelegation)
 userproxy = mypclient.logonRenewMyProxy(username=sha1(sys.argv[4]+userdn).hexdigest(), myproxyserver=myproxyserver, myproxyport=7512)
-print "Proxy Retrieved with len ", len(userproxy)
+print("Proxy Retrieved with len ", len(userproxy))
--- ./doc/generate_modules.py	(original)
+++ ./doc/generate_modules.py	(refactored)
@@ -7,6 +7,7 @@
 creates ReST files appropriately to create code documentation with Sphinx.
 It also creates a modules index (named modules.).
 """
+from __future__ import print_function
 
--- ./src/python/CRABInterface/RESTFileTransfers.py	(original)
+++ ./src/python/CRABInterface/RESTFileTransfers.py	(refactored)
@@ -1,3 +1,4 @@
+from __future__ import print_function
 # WMCore dependecies here
 from WMCore.REST.Server import RESTEntity, restcall
 from WMCore.REST.Validation import validate_str, validate_num, validate_strlist
@@ -29,7 +30,7 @@
                 authz_operator_without_raise('crab3', 'operator')):
             # TODO: do not forget to uncomment this
             # so far just print a warning
-            print 'WARNING. NOT AUTHORIZED'
+            print('WARNING. NOT AUTHORIZED')
             #raise ForbiddenAccess('Access is restricted to this API')
         if method in ['PUT']:
             raise UnsupportedMethod('This method is not supported in this API!')
--- ./src/python/CRABInterface/RESTFileUserTransfers.py	(original)
+++ ./src/python/CRABInterface/RESTFileUserTransfers.py	(refactored)
@@ -1,3 +1,4 @@
+from __future__ import print_function
 # WMCore dependecies here
 from WMCore.REST.Server import RESTEntity, restcall
 from WMCore.REST.Validation import validate_str, validate_num, validate_strlist
@@ -32,7 +33,7 @@
             # Now what is put in CouchDB is not validated
             # And all put are prepared by us in JOB wrappers, so it should already be correct.
             # P.S. Validation is done in function and it double check if all required keys are available
-            print param, safe
+            print(param, safe)
             validate_str("id", param, safe, RX_ANYTHING, optional=False)
             validate_str("username", param, safe, RX_ANYTHING, optional=False)
             validate_str("taskname", param, safe, RX_ANYTHING, optional=False)
@@ -261,7 +262,7 @@
             raise InvalidParameter('TaskName is not defined')
         binds['username'] = username
         binds['taskname'] = taskname
-        print binds
+        print(binds)
         if subresource == 'getTransferStatus':
             ###############################################
             # getTransferStatus API
--- ./src/python/TaskWorker/Actions/PostJob.py	(original)
+++ ./src/python/TaskWorker/Actions/PostJob.py	(refactored)
@@ -100,6 +100,7 @@
 from ServerUtilities import isFailurePermanent, parseJobAd, mostCommon, TRANSFERDB_STATES, PUBLICATIONDB_STATES, encodeRequest, isCouchDBURL, oracleOutputMapping
 
 from WMCore.Configuration import Configuration, ConfigSection
+from functools import reduce
 
 
 ASO_JOB = None
--- ./src/python/TaskWorker/Actions/Recurring/GenerateXMLForTW.py	(original)
+++ ./src/python/TaskWorker/Actions/Recurring/GenerateXMLForTW.py	(refactored)
@@ -82,7 +82,7 @@
             result = coll.query(htcondor.AdTypes.Schedd,'CMSGWMS_Type=?="crabschedd"',['Name','ShadowsRunning','TotalSchedulerJobsRunning','TotalIdleJobs','TotalRunningJobs','TotalHeldJobs'])
             for schedd in result:  # oneshadow[0].split('@')[1].split('.')[0]
                 data.append([schedd['Name'],schedd['ShadowsRunning'],schedd['TotalSchedulerJobsRunning'],schedd['TotalIdleJobs'],schedd['TotalRunningJobs'],schedd['TotalHeldJobs']])
-        except  Exception, e:
+        except  Exception as e:
             self.logger.debug("Error in getShadowsRunning: %s"%str(e))
         return data
 
@@ -125,7 +125,7 @@
             for name in ['SUBMITTED', 'FAILED', 'QUEUED', 'NEW', 'KILLED', 'KILLFAILED', 'RESUBMITFAILED', 'SUBMITFAILED']:
                 numericval = SubElement(data, "numericvalue")
                 numericval.set("name","number_of_%s_tasks_in_the_last_minute"%(name))
-                if twStatus.has_key(name):
+                if name in twStatus:
                     numericval.text = str(twStatus[name])
                 else:
                     numericval.text = '0'
@@ -143,7 +143,7 @@
             for name in ['KILL', 'RESUBMIT', 'NEW', 'QUEUED', 'KILLFAILED', 'RESUBMITFAILED', 'SUBMITFAILED', 'UPLOADED']:
                 numericval = SubElement(data, "numericvalue")
                 numericval.set("name","numberOfTasksIn_%s_State"%(name))
-                if twStatus.has_key(name):
+                if name in twStatus:
                     numericval.text = str(twStatus[name])
                 else:
                     numericval.text = '0'
@@ -203,7 +203,7 @@
             with open(temp_xmllocation, 'w') as f:
                 f.write(tostring(root))
             os.system('mv %s %s' % (temp_xmllocation, self.xmllocation))
-        except Exception, e:
+        except Exception as e:
             self.logger.debug(str(e))
 
 if __name__ == '__main__':
@@ -231,6 +231,6 @@
     cmd = "curl -i -F file=@/home/crab3/CRAB3_SCHEDD_XML_Report2.xml xsls.cern.ch"
     try:
         pu = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
-    except Exception, e:
+    except Exception as e:
         logger.debug(str(e))
 
 
            


```

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
These comments about tabs instead of spaces and not having multiples of 4 spaces are not good. It's possible to cause logic errors this way if some parts are indented correctly and other parts are not. They should be fixed.

**Comment by belforte** [comment]
test this please

**Comment by ericvaandering** [comment]
When you push a new commit, tests should be triggered automatically. Only if Jenkins fails or you think you have a spurious error should you need to ask for a new new test run

**Pull request merged**
