### PR TITLE
Fix for RUCIO task process

### PR DESCRIPTION
**Pull request by dciangot**
Fix a typo introduced with the latest cleanup of rucio registration code.

### CODE REVIEW

**Comment by belforte** [comment]
please test

**Comment by amaltaro** [comment]
test please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by amaltaro** [comment]
test this please

**Comment by belforte** [comment]
@dciangot the PR itself is fine. But now that Alan and Daina made Jenkins work again, we need to address the pylint errors (even if so far I can't read the report becaue it gives me header too large error). Let me know if you like it to merged anyhow.

**Comment by dciangot** [comment]
> @dciangot the PR itself is fine. But now that Alan and Daina made Jenkins work again, we need to address the pylint errors (even if so far I can't read the report becaue it gives me header too large error). Let me know if you like it to merged anyhow.

Ok, let me try to fix it first. I'll let you know.

**Comment by belforte** [comment]
test this

**Comment by belforte** [comment]
test please

**Comment by belforte** [comment]
test

**Comment by belforte** [comment]
please test

**Comment by belforte** [comment]
test this please

**Comment by belforte** [comment]
Note: the Python3 compatibility test failure has been fixed in another PR: #6087

**Comment by belforte** [comment]
@ddaina please merge anyhow and open a new issue about fixing the pylint issues.  Then it is best if you can take care of the serious errors yourself and leave minor things for a future time.

**Comment by belforte** [comment]
@ddaina never mind. I discovered that I can edit Diego's branch and I fixed the pylint W1201 and W016 myself. The python3 compatibility were fixed in a different PR.

**Comment by belforte** [comment]
cool. All Jenking checks passed !

**Pull request merged**
