### PR TITLE
PostJob write to error summary for alien jobid/retry only if job exit code != 0.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**
This is for @juztas to try before merging.

### CODE REVIEW

**Comment by juztas** [comment]
@AndresTanasijczuk I can not test it. See https://github.com/dmwm/CRABServer/issues/4784

**Comment by juztas** [comment]
@AndresTanasijczuk so with changes what we did together it helped a bit, but not fully. It is still showing Invalid framework job report. Please see this task http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=1074095

**Comment by juztas** [comment]
@AndresTanasijczuk I want to comment about your pull request and I think here should be two separate pull requests:
a) Changing code to reflect needed functionality;
b) Changing code by renaming variable names and have nicer code

Also this pull request partially solves our problem, but not covering it fully.

**Comment by mmascher** [comment]
Moving the discussion to the ticket.

**Pull request merged**
