### PR TITLE
Fix 7346

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
in test in crab-dev-tw01. One manual task OK. Now sending Jenkins 
@mapellidario I asked for your review simply because you may need to get familiar with all this. So it is a chance to start. Feel free to ask me. And maybe optParser is a bit different in py3

**Comment by mapellidario** [comment]
I think your solution would work, but I would use something that allows a bit more flexibility when calling the script, like [1].

[1] https://stackoverflow.com/a/43357954

**Comment by belforte** [comment]
thanks Dario. I am not sure it is worth the effort now. But maybe as part of porting to py3 you can review this and simplify.
tests were OK (one Jenkins task is stuck with xfer errors, but it is unrelated). So I will fix a couple pylint warnings and then would like to merge. Please finalize your review.

**Review by mapellidario — APPROVED** [review]
Thanks Stefano, looks good to me.

I agree on evaluating if suggestions from [1] are worth as part of #7084

[1] https://github.com/dmwm/CRABServer/pull/7347#issuecomment-1193787860

**Pull request merged**
