### PR TITLE
Print full TW checkwrite error message. Fix #5240

### LINKED ISSUE #5240: TW log should show details of failure of checkwrite
currently TW log only say that check of writing to remote SE failed, it prints the command, but not the error message. This is annoying exp. because there are cases where the SRM write is failing during crab submit but works when user does crab checkwrite.

### PR DESCRIPTION
**Pull request by emaszs**

### CODE REVIEW

**Comment by belforte** [comment]
could you print stdout as well ?

**Comment by emaszs** [comment]
@belforte of course. This is what `crab status` looks like when the TaskWorker checkwrite fails:
```
[erupeika@lxplus077 ~]$ crab st
CRAB project directory:		/afs/cern.ch/user/e/erupeika/crab_projects/crab_stageout_check14
Task name:			160722_133301:erupeika_crab_stageout_check14
Task status:			SUBMITFAILED
Failure message:		CRAB3 refuses to send jobs to grid scheduler for 160722_133301:erupeika_crab_stageout_check14. Error message: Permission denied. Can't submit task because write check at destination site fails. Please check that you have write access to destination site and that your quota is not exceeded, use crab checkwrite for more informations.
				Copying 85 bytes file:///data/srv/TaskManager/3.3.1604.rc1/160722133301erupeikacrabstageoutcheck14_crab3check.tmp => srm://cit-se.ultralight.org:8443/srm/v2/server?SFN=/mnt/hadoop/store/user/erupeika/160722133301erupeikacrabstageoutcheck14_crab3check.tmp
				event: [1469194393852] BOTH   GFAL2:CORE:COPY	LIST:ENTER	
				event: [1469194393852] BOTH   GFAL2:CORE:COPY	LIST:ITEM	file:///data/srv/TaskManager/3.3.1604.rc1/160722133301erupeikacrabstageoutcheck14_crab3check.tmp => srm://cit-se.ultralight.org:8443/srm/v2/server?SFN=/mnt/hadoop/store/user/erupeika/160722133301erupeikacrabstageoutcheck14_crab3check.tmp
				event: [1469194393852] BOTH   GFAL2:CORE:COPY	LIST:EXIT	
				event: [1469194394016] BOTH   SRM	PREPARE:ENTER	
				
				WARNING Transfer failed with: DESTINATION MAKE_PARENT srm-ifce err: Input/output error, err: [SE][Mkdir][SRM_FAILURE] httpg://cit-se.ultralight.org:8443/srm/v2/server: srm://cit-se.ultralight.org:8443/srm/v2/server?SFN=/mnt/hadoop/store/user/erupeika: Error:/bin/mkdir: cannot create directory `/mnt/hadoop/store/user/erupeika': Permission denied
				Ref-u uscms5212  /bin/mkdir /mnt/hadoop/store/user/erupeika
				
				gfal-copy error: 5 (Input/output error) - DESTINATION MAKE_PARENT srm-ifce err: Input/output error, err: [SE][Mkdir][SRM_FAILURE] httpg://cit-se.ultralight.org:8443/srm/v2/server: srm://cit-se.ultralight.org:8443/srm/v2/server?SFN=/mnt/hadoop/store/user/erupeika: Error:/bin/mkdir: cannot create directory `/mnt/hadoop/store/user/erupeika': Permission denied
				Ref-u uscms5212  /bin/mkdir /mnt/hadoop/store/user/erupeika
				
				
Log file is /afs/cern.ch/user/e/erupeika/crab_projects/crab_stageout_check14/crab.log
```
This is also printed multiple times in the twlog.txt as well as the taskworker task log, found in /data/srv/TaskManager/current/logs/tasks/$USER.

**Comment by belforte** [comment]
I know what message looks like, but am not sure that in general there will never be useful info in stdout, even if in case of this particular error nothing was printed to stdout.
About duplication in multiple logs, IIUC this is a more general feature of TW. We can surely review it, but it is not specific of stageout check failure.

**Comment by emaszs** [comment]
Just posted it to make sure we're talking about the same thing. I also think it's a lot easier to notice if it's printed multiple times, so maybe that's not an issue at all :)

**Comment by belforte** [comment]
I epxect to only need to look at this when investigating user submission error, i.e. in the context of a specific task. So full detail in task/username/taskname.log is enough. But I do not know how to send output to one log only rather then all the 3 ones (twlog, process.log, task.log). Up to you. Hopefully we rotate and cleanup TW logs before we run out of disk space (to check with Jadir).

**Comment by jmarra13** [comment]
Well TW logs are rotate every day at midnight but they are not compressed, what can be easily addressed with a cron job.

**Pull request merged**
