### PR TITLE
Exclude secondary files with no lumis to analyze.

### LINKED ISSUE #5061: Incorrect outfilelumis parameter
Is this known? 
http://submit-4.t2.ucsd.edu/CSstoragePath/77/uscms5930/151103_163809:wulsin_crab_candidateTrackProducer_SingleMuon_2015D_v3/postjob.237.2.txt

```
Tue, 03 Nov 2015 21:33:55 PST(+0000):DEBUG:PostJob Uploading file metadata for miniAODWithCandidateTracks.root to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [('outlfn', '/store/user/wulsin/SingleMuon/Run2015D-05Oct2015-v1/151103_163809/0000/miniAODWithCandidateTracks_237.root'), ('outdatasetname', u'/SingleMuon/wulsin-Run2015D-05Oct2015-v1-648b8b56b17f056199dda35df48180f8/USER'), ('globalTag', 'None'), ('checksumadler32', u'55716676'), ('pandajobid', 237), ('checksumcksum', u'969482382'), ('outlocation', 'T3_US_OSU'), ('outtmplfn', '/store/temp/user/wulsin.cfa6996acb60007a8a99da762cf957b129a9baf9/SingleMuon/Run2015D-05Oct2015-v1/151103_163809/0000/miniAODWithCandidateTracks_237.root'), ('outsize', 2214152620), ('appver', 'CMSSW_7_4_12_patch4'), ('outtype', 'EDM'), ('checksummd5', 'asda'), ('publishdataname', u'Run2015D-05Oct2015-v1-648b8b56b17f056199dda35df48180f8'), ('taskname', '151103_163809:wulsin_crab_candidateTrackProducer_SingleMuon_2015D_v3'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_UCSD'), ('events', 35404), ('directstageout', 0), ('outfileruns', '257394'), ('outfileruns', '256941'), ('outfilelumis', '41,42,43,44,45,56,57,68,69,70'), ('outfilelumis', '251,252,253,254,255,257,258,259,260,261,262,268,269,270,290,293,294'), ('inparentlfns', '/store/data/Run2015D/SingleMuon/MINIAOD/05Oct2015-v1/30000/4407562C-956F-E511-BFEA-0025905A612C.root'), ('inparentlfns', '/store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/0C7BB443-DD61-E511-80A5-02163E014691.root'), ('inparentlfns', '/store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/D6F50C47-EC61-E511-A3E5-02163E0121C6.root'), ('inparentlfns', '/store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/58881C19-FB61-E511-85CE-02163E0146E2.root'), ('inparentlfns', '/store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/D6F50C47-EC61-E511-A3E5-02163E0121C6.root'), ('inparentlfns', '/store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/948D60AB-0662-E511-B3CD-02163E011F3B.root'), ('inparentlfns', '/store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/257/394/00000/70A3C1CB-1864-E511-B0F5-02163E0142D8.root'), ('inparentlfns', '/store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/257/394/00000/588E61BC-1E64-E511-B9B6-02163E014681.root')]
Tue, 03 Nov 2015 21:33:56 PST(+0000):INFO:PostJob ====== Finished upload of output files metadata.
Tue, 03 Nov 2015 21:33:56 PST(+0000):INFO:PostJob ====== Starting upload of input files metadata.
Tue, 03 Nov 2015 21:33:56 PST(+0000):DEBUG:PostJob Uploading file metadata for input file /store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/0C7BB443-DD61-E511-80A5-02163E014691.root
Tue, 03 Nov 2015 21:33:57 PST(+0000):DEBUG:PostJob Uploading file metadata for input file /store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/D6F50C47-EC61-E511-A3E5-02163E0121C6.root
Tue, 03 Nov 2015 21:33:58 PST(+0000):DEBUG:PostJob Uploading file metadata for input file /store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/58881C19-FB61-E511-85CE-02163E0146E2.root
Tue, 03 Nov 2015 21:34:00 PST(+0000):DEBUG:PostJob Uploading file metadata for input file /store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/D6F50C47-EC61-E511-A3E5-02163E0121C6.root
Tue, 03 Nov 2015 21:34:01 PST(+0000):DEBUG:PostJob Uploading file metadata for input file /store/data/Run2015D/SingleMuon/AOD/PromptReco-v3/000/256/941/00000/948D60AB-0662-E511-B3CD-02163E011F3B.root
Tue, 03 Nov 2015 21:34:02 PST(+0000):ERROR:PostJob Error uploading input file metadata: {'Content-Length': '714', 'X-Error-Http': '400', 'X-Rest-Time': '3165.007 us', 'Server': 'CherryPy/3.2.2', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=10812 t=1446615242112916', 'X-Rest-Status': '302', 'Date': 'Wed, 04 Nov 2015 05:34:02 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': "Incorrect 'outfilelumis' parameter", 'X-Error-Id': '87b3287578c40a2034595e60fb892d83'}
Tue, 03 Nov 2015 21:34:08 PST(+0000):ERROR:PostJob Fatal error uploading input files metadata: 
Traceback (most recent call last):
  File "TaskWorker/Actions/PostJob.py", line 1552, in execute_internal
    self.upload_input_files_metadata()
  File "TaskWorker/Actions/PostJob.py", line 1826, in upload_input_files_metadata
    self.server.put(self.rest_uri_no_api + '/filemetadata', data = urllib.urlencode(configreq))
  File "RESTInteractions.py", line 75, in put
    return self.makeRequest(uri = uri, data = data, verb = 'PUT')
  File "RESTInteractions.py", line 113, in makeRequest
    capath=caCertPath)#, verbose=True)# for debug
  File "WMCore/Services/pycurl_manager.py", line 172, in request
    raise exc
HTTPException
Tue, 03 Nov 2015 21:34:08 PST(+0000):INFO:PostJob ====== Finished upload of input files metadata.
```

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**
Requires https://github.com/dmwm/WMCore/pull/6417

I tested this PR running the same task as I described in the issue #5061 
The result is what I expected, that the secondary input (parent) files which have no lumis to be analyzed are not included in the list of input files for the jobs and therefore they do not appear in the FJR.
This is the task in dashboard: http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=151127_201402%3Aatanasi_crab_test_parents_4
This is the relevant part of the job_fjr.1.0.json:
```
...
{"cmsRun": {
"analysis": {},
"cleanup": {},
"errors": [],
"input": {"source": [
{"catalog": "", "events": 919, "guid": "003B900F-E9EE-E111-834F-00259073E3A0", "input_source_class": "PoolSource", "input_type": "primaryFiles", "lfn": "/store/data/Run2012C/SingleMu/AOD/24Aug2012-v1/00000/003B900F-E9EE-E111-834F-00259073E3A0.root", "module_label": "source", "pfn": "root://cmsxrootd-site.fnal.gov//store/data/Run2012C/SingleMu/AOD/24Aug2012-v1/00000/003B900F-E9EE-E111-834F-00259073E3A0.root", "runs": {"198271": [749]}},
{"catalog": "", "events": 919, "guid": "E2EEB799-60C6-E111-B84C-0025901D631E", "input_source_class": "PoolSource", "input_type": "secondaryFiles", "lfn": "/store/data/Run2012C/SingleMu/RAW/v1/000/198/271/E2EEB799-60C6-E111-B84C-0025901D631E.root", "module_label": "source", "pfn": "root://cmsxrootd-site.fnal.gov//store/data/Run2012C/SingleMu/RAW/v1/000/198/271/E2EEB799-60C6-E111-B84C-0025901D631E.root", "runs": {"198271": [749]}}
]},
"logs": {},
"output": {"analysis": [], "output1": [
{"branch_hash": "536a5ef195df9f8c657c867ef96c6dfa", "catalog": "", "checksums": {"adler32": "7ce8ae2e", "cksum": "4177915558"}, "direct_stageout": true, "events": 919, "guid": "04B914F4-4495-E511-B92B-0CC47A4D76CC", "input": ["/store/data/Run2012C/SingleMu/AOD/24Aug2012-v1/00000/003B900F-E9EE-E111-834F-00259073E3A0.root", "/store/data/Run2012C/SingleMu/RAW/v1/000/198/271/E2EEB799-60C6-E111-B84C-0025901D631E.root"], "inputpfns": ["root://cmsxrootd-site.fnal.gov//store/data/Run2012C/SingleMu/AOD/24Aug2012-v1/00000/003B900F-E9EE-E111-834F-00259073E3A0.root", "root://cmsxrootd-site.fnal.gov//store/data/Run2012C/SingleMu/RAW/v1/000/198/271/E2EEB799-60C6-E111-B84C-0025901D631E.root"], "lfn": "", "module_label": "output1", "ouput_module_class": "PoolOutputModule", "pfn": "output1.root", "pset_hash": "7d4851d47bb073facc0d96017716ee10", "runs": {"198271": [749]}, "size": 42781292, "storage_site": "T2_US_Nebraska"}
]},
...
```
This is the result of 'crab report':
```
2 files have been processed
3794 events have been read
1897 events have been written
Analyzed luminosity sections written to /afs/cern.ch/work/a/atanasi/crab3/CMSSW_7_4_12_patch4/src/crab_test_parents_4/results/lumiSummary.json
Log file is /afs/cern.ch/work/a/atanasi/crab3/CMSSW_7_4_12_patch4/src/crab_test_parents_4/crab.log
```

### CODE REVIEW

**Comment by AndresTanasijczuk** [comment]
I made this PR originally to fix #5061, but that issue is solved by https://github.com/dmwm/CRABServer/pull/5097
The only usefulness of this PR is now to avoid having in the FJR unused secondary files in the list of inputs of an output file.

**Comment by belforte** [comment]
but.. isn't FJR written by cmsRun ? Why do we want to remove or add things ?
THis PR also appears to have more stuff like rearrangement of messages (for py2.7 ?).
I don't understand if you think this is worth merging or not. #5097 seems fine to me.

**Comment by AndresTanasijczuk** [comment]
This PR is to not include in the list of parents-of-the-primary-input passed to a job the secondary files that have no lumis to be analyzed by the job. And this is to avoid that these unused secondary files end up appearing in the FJR as inputs contributing to the output file. And the reason to avoid that is to not include these unused secondary input files as parents of the output file in DBS.
But you can achieve the same goal by simply removing unused secondary files from the JSON job report.

Yes, there are some messages rearrangements. No, they are not because of py2.7. I do that hoping that the code becomes visually easier to read (at least it does so for me).

**Comment by belforte** [comment]
but now we understand that all those secondary files listed in FJR are indeed proper parents, simply the run/lumi info for them was wrong. i.e. we should pick the list of file names in FJR as good, and in case it is not, have CMSSW people fix it. But not try to second guess their list, expecially based on wrong info that will anyhow disappear.
So I am afraid you should make a new PR with only the improved messages.
Of course I may have misunderstood something... feel free to point that out, please !

**Comment by bbockelm** [comment]
Hi @belforte 

You're thinking about when the job has completed - FJR and whatnot.

Andres is looking at which files we add to the pset.py.  If we can remove unnecessary files (for example, those that can be excluded by lumimask) from the secondary input file list, we gain efficiency.

Andres - are you adding new calls to DBS here?  How many per dataset?  How heavy are they?

Brian

**Comment by belforte** [comment]
Brian, do you now want to optimize the effort cmsRun has to do in order to
open the needed secondarly file(s) only among a  list of several which may
include extra ones ? There's always room to do better, but.. I doubt
we would have ever put this on our radar had we not hit it accidentally
beacuse we were sending to Couch a metadata file with a list of runs and lumis
that were not used anywhere.
Let's start from a problem that we nees to solve, then we can look at code.
Mergin PR's only because they have been written is not good IMHO.

but maybe I should read the code first ? Say "yes" and I shut up !

**Comment by bbockelm** [comment]
Hi Stefano,

I think it's at least worth asking the question - I do not imply a deep investigation on the topic though.  Just because we stumbled onto a problem accidentally doesn't mean it's not worth looking at.

My concern is that it appears there are quite a few DBS calls added in the PR.  That means there's "cost" for computing to do this, so we need to understand how much "benefit".

How much time does this save per file within CMSSW?  Is it more or less than the time per DBS call?

Brian

**Comment by AndresTanasijczuk** [comment]
@bbockelm Yes, I am adding calls to DBS: one call to `listFilesInBlockWithParents(blockName, lumis=True, validFileOnly=0)` per block of the input dataset. As of how heavy the call is, I don't know what is the measure, but the response contains the lumis for each parent file, which I guess is heavy info. But notice that the new calls are done only when the user has specified useParent = True. CRAB provides two ways in which a user can add secondary files: 1) by setting `useParent = True`, 2) by passing a `secondaryInputDataset`. In the second case the lumis of the secondary files were already available, because there was already a DBS query to get the details of the secondary input dataset. But for `useParent = True`, there was no existing info about the lumis of the secondary files. And maybe one can do it simpler if one can be sure that all parent files belong to a dataset, get what is that dataset, and then work as in the `secondaryInputDataset` case. I am not saying what I did is the best; I was planing to discuss with @belforte next week when he will be at CERN.

@belforte I think I agree with your last comment, because naively I don't think we gain much by avoiding secondary input files in the pset.py that cmsRun will just open/close. Or maybe @bbockelm had something else in mind when he said "improved efficiency"? That's why I doubt in the usefulness of this PR. But if we don't include this PR, I think we have to -by some other means- not include the unused secondary files in the list of parents of a published dataset. And having a patch for that is probably less intuitive than having this PR. 
But ... there is still the unanswered question on whether when publishing a dataset in DBS we should list as parents only the primary input files or as well any other file that has contributed to the data. If we have to only list primary input files, then I see even less value in this PR, because we will have to anyway add code to parse and filter information about input files in the FJR.

**Comment by belforte** [comment]
Given the day and time, and that this is not really trivial, let's indeed
cover this next week face to face.I am even more puzzled now, because support
for seconday dataet and useParent was there already. What's there to add ?


On 12/04/2015 04:13 PM, Andres Tanasijczuk wrote:
> @bbockelm <https://github.com/bbockelm> Yes, I am adding calls to DBS: one call to
> |listFilesInBlockWithParents(blockName, lumis=True, validFileOnly=0)| per block of the input
> dataset. As of how heavy the call is, I don't know what is the measure, but the response contains
> the lumis for each parent file, which I guess is heavy info. But notice that the new calls are done
> only when the user has specified useParent = True. CRAB provides two ways in which a user can add
> secondary files: 1) by setting |useParent = True|, 2) by passing a |secondaryInputDataset|. In the
> second case the lumis of the secondary files were already available, because there was already a DBS
> query to get the details of the secondary input dataset. But for |useParent = True|, there was no
> existing info about the lumis of the secondary files. And maybe one can do it simpler if one can be
> sure that all parent files belong to a dataset, get what is that dataset, and then work as in the
> |secondaryInputDataset| case. I am not saying what I did is the best; I was planing to discuss with
> @belforte <https://github.com/belforte> next week when he will be at CERN.
>
> @belforte <https://github.com/belforte> I think I agree with your last comment, because naively I
> don't think we gain much by avoiding secondary input files in the pset.py that cmsRun will just
> open/close. Or maybe @bbockelm <https://github.com/bbockelm> had something else in mind when he said
> "improved efficiency"? That's why I doubt in the usefulness of this PR. But if we don't include this
> PR, I think we have to -by some other means- not include the unused secondary files in the list of
> parents of a published dataset. And having a patch for that is probably less intuitive than having
> this PR.
> But ... there is still the unanswered question on whether when publishing a dataset in DBS we should
> list as parents only the primary input files or as well any other file that has contributed to the
> data. If we have to only list primary input files, then I see even less value in this PR, because we
> will have to anyway add code to parse and filter information about input files in the FJR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/pull/5095#issuecomment-161990368>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by belforte** [comment]
for the record, I set next to Andres who patiently explained me things and I finally understood.
Allow me to summarize:
1. we already agreed that crabreport only lists run/lumi info from primary input and no other "input file metadata" is sent to Couch.
2. the PR serves two purposes then:
2-a. optimize cmsRun work at run time by not listing as secondary inputs files which do not contain events in the input run/lumi list (after lumimask and runselection have been applied).
2-b. avoid listing those files as events, since in the end no data from those files was used.

I think 2-a. is not worth doing, until at least we have indication of a significant efficiency loss.
On the other hand 2-b. makes sense.

And as in last comment from @AndresTanasijczuk we should address it in the context of "which exactly are the parents" ? and as pointed out already make sure we do not list "parents of parents".

I am not ready to draw a final conclusion yet.

**Comment by AndresTanasijczuk** [comment]
After a second discussion with @belforte we decided that this PR is not really necessary, that we can leave things as they are now. So I am closing it.

**Comment by belforte** [comment]
for the record we agreed that adding code to make a perfect list of parent is not worth.

It is very likely that we list grandparents together with parents when user specified `use_parent=1`, but since we need to support the general use case when the secondary input is a generic dataset, we can't simply ignore secondary files listed in the FJR. Adding a lot of ad hoc code is effort, risk and gain is uncertain and minimal at least.

cmsRun  writes a FJR with a list of output files, and for each output file lists which input files contributed to it. CRAB takes that list and saves in in DBS as Parents.
This has clear benefits:
is simple, clear, and any question about files listed but not used is for cmsRun to solve.

**Pull request closed without merging**
