### PR TITLE
Remove condor_q call on dag_bootstrap_startup. 

### PR DESCRIPTION
**Pull request by juztas**
Please do not merge until we will have 8.3.2 version in all CRAB3 schedulers.

### CODE REVIEW

**Comment by belforte** [comment]
I was curious enough to look at the code. Seems to me that there is no provision for $_CONDOR_JOB_AD never to appear, which is rare, but can happen. Code should not just plow on.

THis is not new, already previous code has no protection against condor_q failing. At least I see nothing that would throw a clear error and take any action other then possibly failing later on in some more or less obscure way. By the way this dag_bootsrap is full of checks whether  $_CONDOR_JOB_AD exits but initially it forces it to be always defined, https://github.com/juztas/CRABServer/blob/condor_q/scripts/dag_bootstrap_startup.sh#L44-L47 , so all statements like if [ "X$_CONDOR_JOB_AD" != "X" ]; are useless and only make the code harder to read.
In addition also the comment lines https://github.com/juztas/CRABServer/blob/condor_q/scripts/dag_bootstrap_startup.sh#L48-L49 need reviewing since they do not agree with new code.

At the risk of sounding like a broken record: Crab3 code is expected to last O(10 years) and outlive current developers, please make sure it is simple, clear, well documented and easy to understand for long term maintenance. I suggest that any time we change some source file, we take the chance to improve on that, not make it worst for sake of closing the issue faster.

**Comment by juztas** [comment]
Thanks @belforte for comments. Of course I will review it whenever I will have 8.3.2 up and running and I can fully test it.

**Comment by belforte** [comment]
things may never fail during testing. Yet at times the class ad file will not be there not even 
after the counter ran to the limit. "It works" is not good enough for code that should last more 
then a month. That's all I wanted to say.

**Comment by juztas** [comment]
@bbockelm @belforte Please review

**Comment by bbockelm** [comment]
Hi,

I agree with Stefano on this - I would like to keep the prior code to fallback to condor_q in the case of HTCondor bugs.  Let's keep this around for a year or so as we build confidence.

Maybe we should have a WARNING if the condor_q fallback is used though?

I would also like to keep the code for downloading a separate test tarball from a URL (it's useful for developers).  We can, of course, remove the reference to my test machine ;)

Brian

**Comment by belforte** [comment]
even if it tries condor_q at some point, code must be prepared for "no way to do this" and report errors in some clean way. My point was not what to use as fallback, but the lack of and "on error" exit point.

**Comment by juztas** [comment]
Sorry, I had problems with my local repo, was faster to create new one pull request. https://github.com/dmwm/CRABServer/pull/4662

Closing.

**Pull request closed without merging**
