### PR TITLE
Add message in TW log showing what will DESIRED_SITES be after applying black/white lists.. Fixes #5056

### LINKED ISSUE #5056: Add message in TW log showing what will DESIRED_SITES be after applying black/white lists

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**

### CODE REVIEW

**Comment by belforte** [comment]
I try to make github link this PR to issue #5056

**Comment by belforte** [comment]
@AndresTanasijczuk can you help reviewing this by posting an example of how twlog looks like before and after the cure ?

**Comment by AndresTanasijczuk** [comment]
Here is an example in which the white/black lists have no effect:

Before:
```
2015-10-30 11:58:28,676:DEBUG:DagmanCreator:Ignore locality: True
2015-10-30 11:58:28,676:DEBUG:DagmanCreator:Blocks: ['/SingleMu/Run2012C-24Aug2012-v1/AOD#e1da09d6-eedc-11e1-9ca5-00221959e69e']
2015-10-30 11:58:28,677:DEBUG:DagmanCreator:Locations: [u'T1_US_FNAL']
2015-10-30 11:58:28,677:DEBUG:DagmanCreator:Possible sites: ['T2_BE_IIHE', 'T2_ES_CIEMAT', 'T2_DE_DESY', 'T2_DE_RWTH', 'T2_CH_CERN', 'T2_BE_UCL']
2015-10-30 11:58:28,678:INFO:DagmanCreator:Resulting available sites: ['T2_DE_RWTH', 'T2_ES_CIEMAT', 'T2_DE_DESY', 'T2_BE_IIHE', 'T2_CH_CERN', 'T2_BE_UCL']
```
After:
```
2015-10-30 11:58:28,674:DEBUG:DagmanCreator:CRAB site blacklist: []
2015-10-30 11:58:28,675:DEBUG:DagmanCreator:Site whitelist: ['T2_BE_IIHE', 'T2_ES_CIEMAT', 'T2_DE_DESY', 'T2_DE_RWTH', 'T2_CH_CERN', 'T2_BE_UCL']
2015-10-30 11:58:28,675:DEBUG:DagmanCreator:Site blacklist: ['T2_IT_Legnaro', 'T2_IT_Rome', 'T2_IT_Bari', 'T2_IT_Pisa']
2015-10-30 11:58:28,676:DEBUG:DagmanCreator:Ignore locality: True
2015-10-30 11:58:28,676:DEBUG:DagmanCreator:Blocks: ['/SingleMu/Run2012C-24Aug2012-v1/AOD#e1da09d6-eedc-11e1-9ca5-00221959e69e']
2015-10-30 11:58:28,677:DEBUG:DagmanCreator:Locations: [u'T1_US_FNAL']
2015-10-30 11:58:28,677:DEBUG:DagmanCreator:Possible sites: ['T2_BE_IIHE', 'T2_ES_CIEMAT', 'T2_DE_DESY', 'T2_DE_RWTH', 'T2_CH_CERN', 'T2_BE_UCL']
2015-10-30 11:58:28,678:INFO:DagmanCreator:Resulting available sites: ['T2_DE_RWTH', 'T2_ES_CIEMAT', 'T2_DE_DESY', 'T2_BE_IIHE', 'T2_CH_CERN', 'T2_BE_UCL']
2015-10-30 11:58:28,678:DEBUG:DagmanCreator:The site whitelist and blacklist will be applied by the pre-job. This is expected to result in DESIRED_SITES = ['T2_DE_RWTH', 'T2_ES_CIEMAT', 'T2_DE_DESY', 'T2_BE_IIHE', 'T2_CH_CERN', 'T2_BE_UCL']
```

**Comment by mmascher** [comment]
+1 on this. And harmless, it's adding print information in the TW.

**Pull request merged**
