### PR TITLE
Remove HTCondorUtils.py #8339

### PR DESCRIPTION
**Pull request by aspiringmind-code**
See https://github.com/dmwm/CRABServer/issues/8339

### CODE REVIEW

**Comment by belforte** [comment]
did you test this ?

**Comment by aspiringmind-code** [comment]
REST tested locally on K8s pod

crab3@crabserver-69b4975fc7-64ns9:/data/repos/CRABServer$ git checkout vchakrav27/06/24_Issue8339
Branch 'vchakrav27/06/24_Issue8339' set up to track remote branch 'vchakrav27/06/24_Issue8339' from 'vchakrav'.
Switched to a new branch 'vchakrav27/06/24_Issue8339'
crab3@crabserver-69b4975fc7-64ns9:/data/repos/CRABServer$ cd /data
crab3@crabserver-69b4975fc7-64ns9:/data$ ./start.sh -g -d
Stop crabserver service... 97 99 
Removing stale pid file /data/srv/state/crabserver/crabserver.pid
[28/Jun/2024:10:28:31]  INFO: final CherryPy configuration: {'engine.autoreload.on': False,
 'request.methods_with_bodies': ('POST', 'PUT', 'DELETE'),
 'request.show_tracebacks': False,
 'server.environment': 'production',
[...]
[28/Jun/2024:10:32:09]  RESTSQL:DlFSjowYUZIT ENTER cmsweb_crab_9r_dev@int2r CRABInterface.RESTBaseAPI.RESTBaseAPI (GET devtwo workflowdb) inuse=0 idle=1 - Podname=crabserver-69b4975fc7-64ns9 Type=cherrypylog
[28/Jun/2024:10:32:09]  RESTSQL:DlFSjowYUZIT (previously JLEyiCjFpzNh) connected, client: 21.5.0.0.0, server: 19.21.0.0.0, stmtcache: 50 - Podname=crabserver-69b4975fc7-64ns9 Type=cherrypylog
[28/Jun/2024:10:32:09]  RESTSQL:DlFSjowYUZIT ping - Podname=crabserver-69b4975fc7-64ns9 Type=cherrypylog
[28/Jun/2024:10:32:09]  RESTSQL:DlFSjowYUZIT check [select sysdate from dual] - Podname=crabserver-69b4975fc7-64ns9 Type=cherrypylog
[28/Jun/2024:10:32:09]  RESTSQL:DlFSjowYUZIT connection established - Podname=crabserver-69b4975fc7-64ns9 Type=cherrypylog
[...]

**Comment by belforte** [comment]
IIUC that means that crabserver is started. That's good, but you should also use it :-)
Changes in this PR only affect taskworker, by the way.

**Comment by novicecpp** [comment]
The `HTCondorUtils` is also inside `setup.py`. Please remove it too.

https://github.com/dmwm/CRABServer/blob/f37fd44274ed7fbb225036df55538bead2bb0e69/setup.py#L42

We use setup.py when run buildTWTarballs.sh here

https://github.com/dmwm/CRABServer/blob/f37fd44274ed7fbb225036df55538bead2bb0e69/cicd/crabtaskworker_pypi/buildTWTarballs.sh#L52

I am not sure why `buildTWTarballs.sh` did not break when I taught Vijay how to run `./start.sh -g`.

**Comment by aspiringmind-code** [comment]
References to HTCondorUtils.py removed in PR https://github.com/aspiringmind-code/CRABServer/pull/1

**Comment by belforte** [comment]
Vijay, to modify `setup.py` you can simply add a commit to this branch in your local and do a `git push` no need to make a PR

**Review by belforte — APPROVED** [review]

**Comment by belforte** [comment]
@aspiringmind-code was that a new build of TW container which included this change ? The information which you put above indicates that a TW was working, but not which one !

**Comment by aspiringmind-code** [comment]
@belforte 
CONTAINER ID   IMAGE                                                      COMMAND                  CREATED       STATUS       PORTS     NAMES
e2f097b1c73e   registry.cern.ch/cmscrab/crabtaskworker:v3.240618-stable   "tini -- /data/run.sh"   7 days ago    Up 7 days              TaskWorker
of crab-dev-tw05

**Pull request merged**
