### PR TITLE
Disable direct stageout for Rucio + better exception management

### PR DESCRIPTION
**Pull request by dciangot**
- disable direct stageout:
  - with rucio managing all the transfers --> users not allowed to other replicas anywhere other than temp RSE
- manage Rucio failures --> propagating failure to transferdb
- use the definitive rucio user namespace: /store/user/rucio/<username>

### CODE REVIEW

**Comment by belforte** [comment]
@dciangot is this ready for merging ? I can do a final pylint cleanup if you like

**Comment by dciangot** [comment]
Yes, it's ready @belforte . If you have time for the pylint I have nothing against it :)

**Comment by belforte** [comment]
I gave it a try at pylint. Will not touch PostJob.py which has many complaints since will need to touch it again in the next day. WIll do then.

**Comment by belforte** [comment]
note: last entry about a commit that referenced this pull request was a typo in the commit message. Ignore it.

**Pull request merged**
