### PR TITLE
Py3 compat fixes

### PR DESCRIPTION
**Pull request by belforte**
this PR contains all fixes described so far in #6388

### CODE REVIEW

**Comment by belforte** [comment]
@ddaina please review that changes are consistenst with https://github.com/dmwm/CRABServer/issues/6388#issuecomment-775188607  
in other words, that I did not slip in something that should not be there
thanks

**Comment by belforte** [comment]
something seems wrong in Jenkins, pylint reports are all empty

**Review by ddaina — COMMENTED** [review]
@belforte , 

1. I reviewed all 4 bullet points, current changes are consistent with the comment. 

2. Regarding Jenkins: I believe problem is here: https://gitlab.cern.ch/CMSDOCKS/dmwm/-/blob/master/crab_tests/CRABScripts/pylintPRCRABServer.sh#L15-18  On line #17 script tries to checkout branch which was not pulled. Here is from Jenkins logs:
```
From https://github.com/dmwm/CRABServer 
 * [new ref]         refs/pull/6395/merge -> PR_MERGE  
From https://github.com/dmwm/CRABServer 
 * [new tag]         v3.210119  -> v3.210119
 * [new tag]         v3.210120  -> v3.210120
 * [new tag]         v3.210120p1 -> v3.210120p1
 * [new tag]         v3.210122  -> v3.210122
 * [new tag]         v3.210127  -> v3.210127
 * [new tag]         v3.210128  -> v3.210128
 * [new tag]         v3.210204  -> v3.210204
error: pathspec 'pythonMigration' did not match any file(s) known to git. ============> where problem comes from
From https://github.com/dmwm/CRABServer 
 ```
 I will have a look how to fix it.

**Comment by belforte** [comment]
thanks. I will merge.
About the Jenkins problem, I suggest not to worry. I think it is the same for WMCore, tests are only run when committing to master branch. That's OK. We can not be 100% perfect.

**Pull request merged**
