### PR TITLE
Use appropriate regex for validating primary dataset name in PrivateMC with no publication.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**

### CODE REVIEW

**Comment by ericvaandering** [comment]
retest this please

**Comment by ericvaandering** [comment]
test this please

**Comment by AndresTanasijczuk** [comment]
@ericvaandering Why is this PR red?

**Comment by ericvaandering** [comment]
Don't know. Perhaps left over from a misconfiguration as I brought up tests on the client. Let me restart it with the magic phrase (which you can use too).

**Comment by ericvaandering** [comment]
test this please

**Pull request merged**
