### PR TITLE
add new functionalities to REST API for ASO

### PR DESCRIPTION
**Pull request by dciangot**
- added feature for getting ASO publication parrallel (e.g. per user)
- fix the retry command (REST call)

### CODE REVIEW

**Comment by dciangot** [comment]
@emaszs can you merge it? I need it in testbed asap to start the final tests.

**Comment by belforte** [comment]
can you give this PR a more descriptive title like "add new functionalities to REST API for ASO" ? and provide a bit of description in the comment so the goal and scope of changes are clear ?

**Comment by emaszs** [comment]
Well I can merge it but testbed deployment is on May 23rd, is it the only place you can test? I could build an RPM and deploy it to our private development CRABServer

**Comment by dciangot** [comment]
I tested it on my vm, but I think that the dev could do work in the meanwhile. thx

**Comment by dciangot** [comment]
@belforte what do you mean more descriptive? from this title you can see that:
- added feature for getting ASO publication parrallel (e.g. per user)
- fix the retry command (REST call)

I can add these point in the description under the title if you prefer

**Comment by dciangot** [comment]
Changed anyhow, I don't mind changing the title indeed

**Comment by emaszs** [comment]
About testing this, ASO/Oracle isn't set up yet on our development instance. But I assume we want this in production ASAP so let's call it critical and I'll ask for an early deployment in testbed.

**Comment by belforte** [comment]
Yes something like that. Don't assume that readers know or can tell. I do not like "fix" w/o saying what the problem was. Simply imagine that someone other than you has to read and understand in 3 years Sent from Stefano's mobile On May 11, 2017 12:24, dciangot <notifications@github.com> wrote:@belforte what do you mean more descriptive? from this title you can see that:
added feature for getting ASO publication parrallel (e.g. per user)fix the retry command (REST call)
I can add these point in the description under the title if you prefer

**Pull request merged**
