### PR TITLE
Fix in loading of previous jobs ads.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**
@juztas Can you confirm if this makes sense? I think what you want to do here is to load all the ads from previous job retries. Isn't it?

### CODE REVIEW

**Comment by juztas** [comment]
and it is doing it right now. Why do you want to change it?

**Comment by AndresTanasijczuk** [comment]
Let say crab_retry = 2. The job ad for crab_retry 2 was already added in https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L94 So in this `for` you want to load (and add to self.ads) the job ads for crab_retries 0 and 1, i.e. `range(0, self.crab_retry)`

**Comment by juztas** [comment]
you are right, sorry

**Comment by AndresTanasijczuk** [comment]
ok

**Comment by AndresTanasijczuk** [comment]
Added:
* a fix of a typo in a message
* a fix of a variable name (job_Ad was undefined -> job_ad_file)
* use os.path.join when defining the path of the job ad files

**Pull request merged**
