### PR TITLE
Fix 5960

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
Needs WMCore 1.2.9 or later. Do not merge yet

**Comment by amaltaro** [comment]
The WMCore fix:
https://github.com/dmwm/WMCore/pull/9400

went in in `1.2.8`

**Comment by belforte** [comment]
Sorry @amaltaro , looks like it was meant to, but it didn't. No big deal. See 1.2.8 here
https://github.com/dmwm/WMCore/blob/1.2.8/src/python/WMCore/FwkJobReport/XMLParser.py
See also this
Screenshot from 2019-11-19 07-43-32
at the top of https://github.com/dmwm/WMCore/pull/9400/commits/e9eebf4c7ce95e99540cd891a855172d07fe1e33

**Comment by amaltaro** [comment]
I got mislead by the "Merge" commit. You're right, it's not in 1.2.8, from the CHANGES file:
https://raw.githubusercontent.com/dmwm/WMCore/master/CHANGES

**Comment by belforte** [comment]
Now testing:
1. built 3.3.1912.patch1 with WMCore 1.2.9  and installed on stefanovm
2.

**Pull request merged**
