### PR TITLE
add file size info to FTS job

### PR DESCRIPTION
**Pull request by dciangot**

### CODE REVIEW

**Comment by dciangot** [comment]
@belforte  this changes should be all. We need to test this somewhere. Once tested we can pass from draft PR to a PR

**Comment by belforte** [comment]
what's the purpose of changing logging level from debug to info ?

**Comment by dciangot** [comment]
Just logical, keeping info for normal operation mode and debug only for manual debugging.

**Comment by belforte** [comment]
ok,so not everything is info.

**Comment by belforte** [comment]
THis will solve  (part of) #5893

**Comment by belforte** [comment]
tested in my VM. OK. Tag and put on preprod.

**Pull request merged**
