### PR TITLE
add crab-task-state.puml

### PR DESCRIPTION
**Pull request by belforte**
as per action item 4.d in [yesterday's meeting](https://docs.google.com/document/d/1HqO_mXG5rFM9BgYhkFiig1h6ltFA80GmGJatA0_5vnA/edit) I have [removed](https://github.com/dmwm/CRABServer/pull/7633) old `doc` directory content and am creating a new `doc/puml` where to store flow/state diagrams which may help to understand the code

### CODE REVIEW

**Comment by belforte** [comment]
@mapellidario @novicecpp see if you like this.

**Comment by novicecpp** [comment]
Shall we put `puml` directory to `etc` or new directory like (yet another) `docs`?
I would like to have another directory at root level for put stuff that not the code but we need to put it in this repo.

**Comment by belforte** [comment]
I like `etc/puml`

**Comment by belforte** [comment]
will make new one with `etc/puml`

**Pull request closed without merging**
