### PR TITLE
Improve message for file size exceeding 100MB.

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**

### CODE REVIEW

**Comment by AndresTanasijczuk** [comment]
This PR is for https://github.com/dmwm/CRABClient/issues/4527 
This PR is not the complete fix. Here I only want to make sure to return to the client the size of the file and a bit better message still with < 200 characters. The rest of the work (print the tar file content sorted by decreasing size) should be done by the client.

**Comment by belforte** [comment]
would it be worth to also print which file this is ? Or will will only be called in very clear situations where other lines are printed already telling what's going on ?

**Comment by belforte** [comment]
I wrote previous comment before reading the second one from Andres... sorry.
Still it seems to me that the needed work is done half in one place, half in another,
would be better all in same place, no ?
For my education, is this modified REST function used by the server, or the client ?

**Comment by AndresTanasijczuk** [comment]
Which "modified REST function" are you referring to Stefano?

In general I think that it is better to do all the work in one place, but in this case I think that showing the content of the sandbox sorting files by size is something the client should do. My reasoning is:
* The server got a request to upload a tar file and if the size of the file is bigger than the allowed limit it should return an error about the file size being bigger than the limit. Period.
* The client is who knows which file it requested for upload, so once it gets the above error it can expand adding additional information in the error message.

What I don't like is that the error the server returns is very general (an InvalidParameter exception) with no particular code or anything that uniquely defines the error. So in the PR I did in the client https://github.com/dmwm/CRABClient/pull/4544 I had to parse the error message, which I don't like, because obviously if some day the message in the server is changed the client side doesn't work anymore.

**Comment by AndresTanasijczuk** [comment]
I forgot to add, error messages in the server (returned via exceptions) have to be < 200 characters: https://github.com/dmwm/CRABServer/issues/4766

**Comment by belforte** [comment]
Never mind. Go ahead. Sorry
On Aug 8, 2015 23:07, Andres Tanasijczuk <notifications@github.com> wrote:Which "modified REST function" are you referring to Stefano?

In general I think that it is better to do all the work in one place, but in this case I think that showing the content of the sandbox sorting files by size is something the client should do. My reasoning is:

The server got a request to upload a tar file and if the size of the file is bigger than the allowed limit it should return an error about the file size being bigger than the limit. Period.The client is who knows which file it requested for upload, so once it gets the above error it can expand adding additional information in the error message.

What I don't like is that the error the server returns is very general (an InvalidParameter exception) with no particular code or anything that uniquely defines the error. So in the PR I did in the client dmwm/CRABClient#4544 I had to parse the error message, which I don't like, because obviously if some day the message in the server is changed the client side doesn't work anymore.

**Pull request merged**
