### PR TITLE
Explicitly disable all transfers for splitting pilots

### PR DESCRIPTION
**Pull request by matz-e**
Not tested yet, I'm fixing my VM right now. Should solve problems observed by Oscar.

### CODE REVIEW

**Comment by matz-e** [comment]
Tested on the dev instance with the offending configuration and two standard tasks without regression. @emaszs, @mmascher could we get this onto preprod?

**Comment by emaszs** [comment]
oops, missclicked the close button. @matz-e, I've deployed the TaskWorker from the dev instance on preprod.

**Comment by matz-e** [comment]
Thank you!

**Comment by emaszs** [comment]
@matz-e Did you manage to test it? Marco wanted to test another thing on testbed's task worker and I didn't include this patch.

**Comment by matz-e** [comment]
Yes, I tested it, and IMHO is ready to be merged.

**Pull request merged**
