### PR TITLE
Allow use new publisher fix6177

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by belforte** [comment]
please test

**Comment by belforte** [comment]
testing again since old Jenkins log is gone and I do not remember.  In lack of any feedback from @dciangot I will review pylint output and merge. We need to move on with testing.

**Comment by belforte** [comment]
test this

**Comment by belforte** [comment]
somehow my attempts to make Jenkins run failed. I had to commit a small change. @ddaina do you know if I used the wrong comment, or simply had the wrong expectation ?

**Comment by ddaina** [comment]
I do not know final list of keywords that triggers Jenkins, but this one should work: `test this please`. 

I will check it and get back to you.

**Comment by belforte** [comment]
test this please

**Comment by belforte** [comment]
OK `test this please` worked, after I tried `test this` and `test please`. I think Jenkins in CMSSW accepts the shorter ones too, so maybe one can add. I find it difficult to remember :-(

**Pull request merged**
