### PR TITLE
Move WMArchiveUploader.py from gitlab to github (fix #6191)

### LINKED ISSUE #6191: Move WMArchiveUploader.py  from gitlab to CRABServer repository
Move [WMArchiveUploader script](https://gitlab.cern.ch/CMSSI/SubmissionInfrastructureScripts/-/blob/master/WMArchiveUploader.py) from gitlab to https://github.com/dmwm/CRABServer/tree/master/src/python

### PR DESCRIPTION
**Pull request by ddaina**

### CODE REVIEW

**Comment by belforte** [comment]
sorry if I am confused. Is this simply a copy and the fix for the stale lock comes next ? Or is this the final thing

**Comment by ddaina** [comment]
Yes, it is a copy. I was planning to move the fix separately.

**Comment by belforte** [comment]
perfect. I get again error when trying to open Jenkins reports...
Bad Message 431  reason: Request Header Fields Too Large
both on FF and Chrome. pff... I think is something related to authentication on cmssdt and cookies... che palle !

**Comment by belforte** [comment]
sorry, I forgot to add last nigh that this is fine.

**Comment by ddaina** [comment]
thank you. Mhmm, regarding `Bad Message 431 reason: Request Header Fields Too Large` I had the same issue and cleaning cookies helped me.

**Pull request merged**
