### PR TITLE
Report the long exit code of job using condor_chirp. Fixes #4615

### LINKED ISSUE #4615: Use chirp to report full exit code as a classAd
Eventually we want ot get rid of the `short exit code = 65` thing. For that I believe we need to modify the `ExitStatus` classad, please correct me if I am wrong.

Notice that the client is already reporting the right exit code (it is taken from the framework job report). This is an example taken from I user task I `remake` on my lxplus account (*). So I am not sure why the dashboard is showing the short one, probably we are taking the wrong exit code? But I think it will be corrected if we chirped the long exit status, which we need to do for glidemon.

(*)
```
[mmascher@lxplus0078 wf]$ crab remake --task=150108_113454_crab3test-2:vormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Enter GRID pass phrase for this identity:
Contacting voms2.cern.ch:15002 [/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch] "cms"...
Remote VOMS server contacted succesfully.


Created proxy in /tmp/x509up_u8440.

Your proxy is valid until Sat Jan 10 10:54:28 CET 2015
WARNING: Incompatible CRABClient version "development"
Server is saying that compatible versions are: ['3.3.12', '3.3.12.patch1', '3.3.12.rc7']
Remaking crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola folder
Remaking the .requestcache for 150108_113454_crab3test-2:vormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Success: Finish making crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola/.requestcache
Log file is /afs/cern.ch/user/m/mmascher/wf/crab.log


[mmascher@lxplus0078 wf]$ crab status crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
WARNING: Incompatible CRABClient version "development"
Server is saying that compatible versions are: ['3.3.12', '3.3.12.patch1', '3.3.12.rc7']
Task name:			150108_113454_crab3test-2:vormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Task status:			FAILED
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150108_113454_crab3test-2%3Avormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=vormwald&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150108_113454_crab3test-2%3Avormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Details:			failed        100.0% (16/16)

No publication information available yet

Error summary:
16 jobs failed with exit code 8001:
	CmsRunFailure
	CMSSW error message follows.
	Fatal Exception
	An exception of category 'PluginNotFound' occurred while
	   [0] Constructing the EventProcessor
	Exception Message:
	Unable to find plugin 'PileupJetIdProducer'. Please check spelling of name.

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes
Log file is /afs/cern.ch/user/m/mmascher/wf/crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola/crab.log
```

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by mmascher** [comment]
Took care of the comments and updated https://twiki.cern.ch/twiki/bin/view/CMSPublic/JobExitCodes

**Comment by belforte** [comment]
@mmascher since you added a new exit code please change also
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py

**Comment by mmascher** [comment]
Thanks Stefano, I was wondering about that.

**Comment by mmascher** [comment]
WMCore PR: https://github.com/dmwm/WMCore/pull/6698

**Pull request merged**
