### PR TITLE
Check disk usage from job.ad

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by mmascher** [comment]
I think MAX_DISK_SPACE should be put in ServerUtilities and be used in DagmanCreator as well (instead of hardcoding its value

**Comment by juztas** [comment]
Ok, Comment why this is needded:
a) If SYSTEM_PERIODIC_REMOVE comes first, there is no Periodic Remove Reason and job is retried.
b) It matches 100GB, while SYSTEM_PERIODIC_REMOVE is set to 27GB

Why 20GB? Because this is what is defined in VOCard and what always should be available on WN.

**Comment by mmascher** [comment]
New PR looks good to me. Thanks Justas.

**Comment by juztas** [comment]
and you did it too fast :D There is one error :/

**Pull request merged**
