### PR TITLE
Report correct exit code to dashboard from PostJob in case of memory/…

### PR DESCRIPTION
**Pull request by juztas**
…walltime/disk removal

PostJob will report correct exit code for any of these removals. Discussion started here: https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2353.html
@hernand @mmascher can we include this in current under validation release?

### CODE REVIEW

**Comment by belforte** [comment]
do we really need to do this in such an ad-hoc way including if on exit code value ?
I would imagine that post jobs does all its magic, then at the end a final exit code
is written to FJR (json or xml up to you) and made available to crab status, the same
code is then sent to dashboard, whatever it is.
What am I missing ?

**Comment by mmascher** [comment]
Are you suggesting to report the exit code no matter what? Here the "final
exit code" has already been written to FJR. I was thinking that we should
only report the exit code from the WN (how dashboard know if a message is
from the WN or from the schedd? They use this information for something)

**Comment by juztas** [comment]
RetryJob is running on scheduler and not WN, on WN you get 137, which means kill, and you don`t know the reason why scheduler decided to kill it.

**Comment by belforte** [comment]
if what reported from WN was final, why is this code needed at all ?
I see Justas already explained :-)
CRAB3 philosophy is that when jobs run out of resources they are killed
by the scheduler (HTC), not by the job wrapper, so the job wrapper does
not know why. Only HTC knows.
Also notice that there is no harm in sending exit code twice to dashboard.

**Comment by juztas** [comment]
updated what we discussed with Marco

@belforte @mmascher

**Comment by mmascher** [comment]
Sounds good to me

**Comment by mmascher** [comment]
For Stefano, we decided to load of the framework job report and set the exit code only in case of a fatal error (meaning there was no FJR produced on the WN). That's to avoid keeping in memory a copy of the fjr in the schedd and to avoid to load the fjr for no reason

**Comment by belforte** [comment]
why would the fjr be kept in schedd memory ?
anyhow, what's important is that postjob
1. runs
2. decides if FJR need to be modified or not
3. does all modifications it thinks are needed
4. updates dashboard (so that if UDP message from WN was lost, here it goes again)

I do not know if you do 4. at crab status time anyhow. But in general it is good that it is done 
more than on WN only. Remember U in UDP means Unreliable.
I do not want to argue about 2. in here. Do as you like.

On 06/04/2015 12:23 PM, Marco Mascheroni wrote:
> For Stefano, we decided to load of the framework job report and set the exit code only in case of a
> fatal error (meaning there was no FJR produced on the WN). That's to avoid keeping in memory a copy
> of the fjr in the schedd and to avoid to load the fjr for no reason
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/pull/4820#issuecomment-108829246>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by mmascher** [comment]
I meant that either you load it more than one time or you you keep it in memory. This is a tradeoff, we load it twice only if no report was produced on the WN (and maybe the postjob set a different error)

**Comment by belforte** [comment]
Postjob only runs once, and I expect it to be a linear procedural sequence, so in theory it should 
not need to do any action twice. So this is likely a detail due to the way the code is written, more 
than anything in the design. Do what you like, but keep it simple. It is a bit disturbing that a 
simple file like the FJR is something we worry about the effort of loading, but this is a different 
matter.

**Comment by AndresTanasijczuk** [comment]
The exit code reported from the PostJob is set into both, JobExitCode and ExeExitCode. I think I have already asked and forgot what is the difference between them, and whether we have to report both or not. In cmscp.py (i.e. from the WN) we only report JobExitCode.

**Comment by mmascher** [comment]
About what is the difference, are you referring to this Andres
https://github.com/dmwm/CRABServer/issues/4688?

**Comment by belforte** [comment]
Marco, your comments in that issues are not consistent.
The second is correct though.

Story is simple:
ExeExitCode = exit code from cmsRun (or user script if they use scriptExe)
JobExitCode = exit code fro the job, which includes things like: there was
    an error before even running cmsRun (environment ?), so ExeExitCode is undefined; or
    there was an error during stageout (even not stageout related, e.g. wall time
    expired by change right then or similar) so in this case ExeExitCode is zero.
If ExeExitCode is non-zero, JobExitCode should be set = ExeExitCode (and I hope it IS).

Dashboard can receive and display separately both, which at times is helpful.
To avoid confusing users we try to have a single ExitCode shown by crab status,
this has to be the same as the JobExitCode.



On 06/05/2015 12:13 PM, Marco Mascheroni wrote:
> About what is the difference, are you referring to this Andres
> https://github.com/dmwm/CRABServer/issues/4688?
>
> On Fri, Jun 5, 2015 at 12:10 PM, Andres Tanasijczuk <
> notifications@github.com> wrote:
>
>  > The exit code reported from the PostJob is set into both, JobExitCode and
>  > ExeExitCode. I think I have already asked and forgot what is the difference
>  > between them, and whether we have to report both or not. In cmscp.py (i.e.
>  > from the WN) we only report JobExitCode.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  > <https://github.com/dmwm/CRABServer/pull/4820#issuecomment-109248200>.
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/pull/4820#issuecomment-109249344>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by AndresTanasijczuk** [comment]
I asked about the names used when reporting to dashboard. What @belforte explained.

**Comment by mmascher** [comment]
Yes, the second commento on that ticket was the right one, I put it there after a discussion in a meeting.

**Comment by AndresTanasijczuk** [comment]
The first place where we report ExeExitCode and/or JobExitCode to dashboard is in the job wrapper (in CMSRunAnalysis.sh and CMSRunAnalysis.py).

In CMSRunAnalysis.sh:
------------------------------
Under any error in the environment setup before calling CMSRunAnalysis.py we report JobExitCode = some of [10031, 10032, 10043] and no ExeExitCode.
RUN CMSRunAnalysis.py
If CMSRunAnalysis.py exits with 68 (CMSSW encountered a malloc failure) or 137 (job was killed in the worker node), we report JobExitCode = 50669 and no ExeExitCode.

In CMSRunAnalysis.py:
------------------------------
In case of early failure (reading arguments to CMSRunAnalysis.py, preparing sandbox, loading WMCore), we report JobExitCode = 10043 and no ExeExitCode:
https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L129-135
Otherwise we report JobExitCode = ExeExitCode = the exit code in the FJR or whatever exit code CMSRunAnalysis.py defines in case of failure:
https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L149-151
Then we have these lines
https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L283-286
in case addReportInfo gives an exception, but I don't see when that can happen.

Then it comes the stage out wrapper, aka cmscp, which reports JobExitCode = cmscp-exit-code in case the later is != 0. And cmscp inherits the job wrapper exit code if the later is != 0.

Then it comes the PostJob with the new code from the present commit (until now PostJob was not reporting exit codes to dashboard). From what Stefano explained, seems to me that here we should not report ExeExitCode, because for example if job was killed, then ExeExitCode should be undefined, or not? 
On the other hand, I didn't understand why fatal error implies FJR not produced in WN. Aren't there fatal errors where FJR is produced in WN? For example, cmscp writes stageout error exit code in FJR['exitCode']. Can't RetryJob interpret it as a fatal error? Maybe not today, but in the future? (e.g. if stageout policy is only 'remote' and user has not write permission in dest storage; that should be fatal stageout error in cmscp.)

**Comment by AndresTanasijczuk** [comment]
Another thing I want to clarify again is that failures in the post-job itself (I am not talking about post-job or retry-job detecting failures from job) do not derive in a post-job exit code reported to users. That is, the post-job doesn't change the exit code in the FJR for post-job failures, but writes a dummy exit code (0 or 90000) in a new FJR section named 'postjob' to let crab status know if the post-job failed or not. If the 'exitCode' in FJR is 0 and crab status finds the 90000 from the post-job, it will show "Post-processing failed" (or similar), but no exit code. This is to be consistent with what dashboard reports and because we don't have the code in place to assign exit codes to different types of failures in the post-job.

In Stefano's proposal:
1. runs 
2. decides if FJR need to be modified or not 
3. does all modifications it thinks are needed 
4. updates dashboard (so that if UDP message from WN was lost, here it goes again)

2. and 3. are only done when the post-job runs the retry-job to detect failures in the job. For example, what Justas wrote, that when a job is killed in the WN, the FJR originally contains exitCode = 137, and then it is the retry-job who knows about the kill reason and updates FJR['exitCode'].
4. was not done before in post-job; it is done now in this new commit, but is not done in all cases, as Marco explained. Why not do it in all cases? I.e. even if a recoverable error?
4. is not done at crab status time.

**Comment by belforte** [comment]
I read a few times, but am finding it difficult to understand what exactly is being done and what the questions are. Maybe because it is getting hot where I am.
I really would like you guys to make your clean 1-2-3-4.. flow and avoid any ad hoc fixing.
IMHO, if postjob fails, the job exit code needs to be changed from 0 to something else and reported to dashboard as well.

**Comment by AndresTanasijczuk** [comment]
Stefano, what you say "if postjob fails, the job exit code needs to be changed from 0 to something else and reported to dashboard as well." is another issue IMO. As I explained, we don't have the code in place today to assign different exit codes to different failure reasons in the postjob. Maybe it is very easy to do because there are not many exit codes that could be used (just stageout error, filemetadata upload error, what else?). But anyway, is still a separate issue.

The two questions I want to get an answer for are:
In the commit from Justas:
1) I think we should not report ExeExitCode to dashboard. Or am I wrong?
2) Why to report only if job failure detected by retry-job is fatal? I think it would not heart to report also in case of recoverable errors, simply because of what Stefano said about lost UDP packets. I understand the problem of "loading the FJR twice or keeping it in memory" that Marco was talking about. So if that's the good reason, then ok, but we have an issue to improve that as well (https://github.com/dmwm/CRABServer/issues/4772).

**Comment by hernand** [comment]
Are postjobs reporting on error always the same error code? which one? and only on fatal (terminal) error? I think they should report the error code also when the job is retried. For example, if the ASO fails, the job is retried, right? Is the ASO failure error code not reported in that case?

Concerning reporting the ExeExitCode, it is probably redundant. If the job succeeds, it is implicit that the application succeeded too. If the job fails because the application failed, the job exit code will the the application exit code, right?

**Comment by AndresTanasijczuk** [comment]
Replying to Jose's questions:

Q: "Are postjobs reporting on error always the same error code? which one? and only on fatal (terminal) error? "
A: postjobs were not reporting any error code to dashboard. They were only reporting the 'StatusValue'. See https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L1835-1848 If the job is going to be resubmitted, it reports 'StatusValue': 'Cooloff'. If the job is NOT going to be resubmitted, it reports 'StatusValue': 'Aborted'.

Q: For example, if the ASO fails, the job is retried, right?
A: If the error is considered recoverable.

Q: Is the ASO failure error code not reported in that case?
A: We don't have error codes (in the sense of https://twiki.cern.ch/twiki/bin/view/CMSPublic/JobExitCodes) for failures in the post-job (or ASO in particular). One can see only "Post-processing failed" in dashboard or glidemon or crab status. The PostJob code does have an exit code of course (0: OK, 1: RECOVERABLE ERROR, 2: FATAL ERROR) used to tell dagman if the job can be resubmitted or not. In case of 0 we report to dashboard 'StatusValue': 'Finished'. In case of 1 we report to dashboard 'StatusValue': 'Cooloff'. In case of 2 we report to dashboard 'StatusValue': 'Aborted'. And dashboard shows the string "post-processing step failed" for both 1 and 2.

Q: Concerning reporting the ExeExitCode, it is probably redundant. If the job succeeds, it is implicit that the application succeeded too. If the job fails because the application failed, the job exit code will the the application exit code, right?
A: This pull from Justas introduces for the first time the reporting of actual error codes from the postjob code to dashboard, where the reported error codes concern only errors occurred in previous steps to the post-job execution; this pull is NOT to report errors occurred in the post-job (in ASO for example). The motivation was, as Justas explained, that when a job is killed by condor, the error code reported to dashboard from the WN is always 137, and is only the post-job who will know the reason of the kill and therefore can report the correct error code (there is one code for kill due to memory, one code for kill due to walltime, etc). So the motivation is clear, but the pull from Justas is not restricted to report only when a job is killed by condor, but reports any fatal error occurred in any step before the post-job execution. So for example, suppose the application succeeded (and ExeExtiCode = 0 was reported to dashboard from WN) but cmscp fails with a fatal error (doesn't matter if that is currently possible or not); the cmscp error code will be reported as JobExitCode to dashboard from the WN first, and then this pull will report it again as JobExitCode (that's fine) and as ExeExitCode (that's what I argue is not correct in such example).

**Comment by hernand** [comment]
ok, Andres, thanks for the explanation. 
So, to make sure I understand: till now failures in ASO were not reported to the dashboard with a proper error code, right? It was only reported the StatusValue Cooloff if the job was going to be resubmitted or Aborted in case the job does not get automatically resubmitted. The dashboard then maps both cases to "Post-processing failed", but which error code is associated by the dashboard in that case? I mean, in the historical view, in this pie chart, 
http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/terminatedjobsstatus_individual?sites=All%20T3210&submissions=crab3&activities=analysis&sitesSort=7&start=null&end=null&timeRange=lastWeek&sortBy=0&granularity=Hourly&generic=0&series=All&type=aaap
which error code corresponds to postprocessing failure???

What is the meaning then of the error codes 6030*? failures in direct stageout?

IMO we urgently need to report to the dashboard failures that the postjob can catch (e.g. failure in transferring the files with ASO). Otherwise we have no idea of the ASO success rate, for example. 

Concerning the ExeExitCode, I agree it should not be changed w.r.t.  what was reported from the WN. I mean ExeExitCode is the exit code of the application. If we want from the postjob to re-send the same ExeExitCode for reliability reasons, fine, but it should not be changed.

**Comment by AndresTanasijczuk** [comment]
Q: So, to make sure I understand: till now failures in ASO were not reported to the dashboard with a proper error code, right?
A: Right.

Q: What is the meaning then of the error codes 6030*? failures in direct stageout?
A: 60307 failure in local and direct stageout. 60302 output file doesn't exit. Both errors reported to dashboard from cmscp.

**Comment by hernand** [comment]
I see. do you have an idea what error code is the dashboard assigning to jobs reported as post-processing failed? they must be somewhere inside the error code dashboard pie chart.

Can Justas extend his work in the dashboard reporting from the postjobs to cover as well post-processing errors such as ASO failure?

**Comment by AndresTanasijczuk** [comment]
Q: do you have an idea what error code is the dashboard assigning to jobs reported as post-processing failed?
A: I don't know...

Q: Can Justas extend his work in the dashboard reporting from the postjobs to cover as well post-processing errors such as ASO failure? 
A: opened https://github.com/dmwm/CRABServer/issues/4831

**Comment by juztas** [comment]
Sure Jose, I will. @mmascher can you assign it to me?

We had disagreement in CRAB3 meeting what I think we should report and what Andres think. And in my first pull request it was done only for killed exit codes, but later it was discussed and said it should be only for FatalError. Andres, I still think it matters if it is possible now or not to fail cmscp with FatalError. Another thing you do not know if it will be reported from WN, UDP packet might not reach dashboard, or it might be that job will be killed before reporting to dashboard with kill -9

I think this is what it should report for killed jobs due to memory/walltime/diskusage:
ExeExitCode = 137
JobExitCode = (Depending what is removal reason) 50660 50662 50664

Please correct me if I am wrong.

**Comment by AndresTanasijczuk** [comment]
To Justas:

Q: Andres, I still think it matters if it is possible now or not to fail cmscp with FatalError.
A: IMHO we should assume that cmscp can give a FatalError. If that is not true today, it can become true tomorrow. Unless there is a design principle that says that cmscp should not produce fatal errors.

Q: Another thing you do not know if it will be reported from WN, UDP packet might not reach dashboard, or it might be that job will be killed before reporting to dashboard with kill -9
A1: Exactly. And that's also why Stefano was saying that we could report to dashboard from post-job not only for fatal errors but always. And I agree. But then it was the issue of loading the FJR twice or load it in memory that I don't want to enter in discussion now and don't intend to fix now. 
A2: Maybe your comment is because I said at some point that we should not report ExeExitCode in your pull? Well, what I meant is that we should not blindly report ExeExitCode = FJR['exitCode'] for any fatal error that retry-job detects, because that implies that we may change what was already reported from WN. Instead we should report ExeExitCode = FJR['jobExitCode'].

Q: I think this is what it should report for killed jobs due to memory/walltime/diskusage:
ExeExitCode = 137
JobExitCode = (Depending what is removal reason) 50660 50662 50664
A: I agree. And I would say the RetryJob should write FJR['jobExitCode'] = 137 when it creates the "fake" FJR.

**Comment by juztas** [comment]
Ok, lets close the loop.
Q: IMHO we should assume that cmscp can give a FatalError
A: Do you have something already in mind?

To tryout, catch and validate all exit codes is not easy and we need for sure to review exit codes in dashboard and fix what we are reporting wrongly or improve. So I propose that we go with baby steps and on Monday I post on crab-dev a list, where you have exit code and task(only for new tasks which are submitted with newest CRAB3 version). Who is participating takes one exit code, and reviews it:
Does it reports correct information?
What is ExeExitCode and JobExitCode (now my script looks only JobExitCode)
Should this job be retried or not? What percentage succeeds after retry?

How sounds?

**Comment by AndresTanasijczuk** [comment]
Q: Do you have something already in mind?
A: Currently error code 60302 is used in cmscp when output file doesn't exit and this is recoverable error. But can this not be treated as FATAL error some day? Or I was imagining the situation in which one day ASO is not working and we put stageout policy "remote" only. If remote stageout fails, it could be because of a condition that we could identify as fatal. True that currently we don't have a granularity to distinguish why a remote stageout failed. But maybe some day... But in general, my point is not about the code today. My point is in making the code robust for today and the future. If that requires lot of effort, then I can understand and agree that it is not worth to do it now. And I know I am not the expert in doing robust things, but I think in this case we can do things more robust with just an easy change as I propose in https://github.com/dmwm/CRABServer/pull/4830 (and don't take this pull as definitive; it can still be refined to accommodate for example your suggestion in previous comment about report for killed jobs ExeExitCode = 137 and JobExitCode = 50660, 50662 or 50664).

I agree we should monitor exit codes in dashboard and review the exit codes. But for me this is independent of the main objection I made about the present pull, which is: I don't think is it generally correct to report ExeExitCode = FJR['exitCode'] for any fatal error.

**Comment by hernand** [comment]
There is something I don't understand: why is there a distinction when reporting a fatal or non-fatal error? what does it mean fatal? that the job will not be resubmitted? jobs that hit the max retry count don't get resubmitted either. In addition, what is considered fatal can depend on time. Why making a distinction in the dashboard reporting?

**Comment by AndresTanasijczuk** [comment]
That was the other point in my original message, and the answer was that when reporting to dashboard we need information from the FJR (basically just the exit code) and this has a high cost in the post-job (either memory-wise if we keep the FJR in memory after the post-job loads it for reading it the first time, or time-wise if we load it again every time we report to dashboard). I personally accepted the answer, because Marco also said that this situation will change after he finishes his current work on refactoring the post-job.

**Pull request merged**
