### PR TITLE
Cleanup job wrapper

### LINKED ISSUE #7705: fix sandbox use in job wrapper
currently `sandbox.tar.gz` is expanded in two places (see  https://github.com/dmwm/CRABServer/pull/7681#issuecomment-1613144037 and comment below that)
1. `/srv` : so that e.g. `scriptExe` and additional `userFiles` are found where needed and as documented in [FAQ](https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#How_are_the_inputFiles_handled_i)
2. `/srv/CMSSW_X_Y_Z` so that "scram subdirectories" picked frome `$CMSSW_BASE` on submission host are placed in corresponding directories

Furthermore, `PSet.py` and `PSet.pkl` are moved up from `/srv/CMSSW_X_Y_Z` to `/srv` because that's the current directory where `cmsRun` command is executed. This overrides the ones places in `/srv` in step 1. 

<strike>
We also have a real problem (**bug**) : new code to expand user tar files https://github.com/dmwm/CRABServer/issues/7661 only does that in `/srv/CMSSW_X_Y_Z`, while user may expect this to be happen in `/srv`
</strike> 
**NO**: reviewing the above one year later, user tar files are expanded in /srv, not /srv/CMSSW_X_Y_Z.  So I am not sure if anything is needed, aside good documentation so that we avoid going through things again.<br><br>

We should expand the sandbox only once and place each file in the right place !

### PR DESCRIPTION
**Pull request by belforte**
fix #7705

### CODE REVIEW

**Comment by belforte** [comment]
tested with a single on on crab-dev-tw01

**Comment by belforte** [comment]
test in CI: https://gitlab.cern.ch/crab3/CRABServer/-/pipelines/8173758

**Comment by belforte** [comment]
@aspiringmind-code you can also look at https://cmscrab.docs.cern.ch/crab-design/crab-job-wrapper.html#new-cmsrunanalysispy for a description of what this PR is supposed to achieve

**Comment by belforte** [comment]
I added one cleanup. WIll test again.

**Comment by belforte** [comment]
Ready for review

**Comment by belforte** [comment]
@aspiringmind-code let me if you think that you do not have the time or feel  not competent to review this.

**Comment by aspiringmind-code** [comment]
Sorry for the delay. I'll do it by tomorrow.

**Comment by aspiringmind-code** [comment]
@belforte I like the use of simpler sandbox argument and the merging of two functions into one. What I still would wanna improve is removing the "moving up the directory" action. IIUC, that will not be required once $CMSSW_BASE files are put inside cmsswVersion directory inside the sandbox. Do we have an open issue regarding that? If yes, this looks good to me. Thanks for my first review opportunity.

**Review by aspiringmind-code — APPROVED** [review]

**Comment by belforte** [comment]
thanks @aspiringmind-code 
I do not like moving files around like that eiher, I thought of this solution in https://github.com/dmwm/CRABServer/issues/7705#issuecomment-2361613880 but have not created an issue
Indeed I thought I did... what I have most is to expand the tarball in two directories

BEst option looks to me at some point to modify sandboxing in client so that $CMSSW_BASE is tarred into a CMSSW_X_Y_Z directory and then all files will automatically go in the proper place when the sandbox is iteratively expanded

**Comment by belforte** [comment]
Well... be my memory be damned. I had not created an issue for the sandbox restructuring in the client, but have already merged a PR to do it !
https://github.com/dmwm/CRABClient/issues/5332

Please have a look and let me now if that addresses your comment

**Comment by aspiringmind-code** [comment]
Yes, this looks perfect.

**Comment by belforte** [comment]
thanks you

**Comment by belforte** [comment]
now the problem will be to remember to cleanup the duplicated untar once new client will be in production

**Pull request merged**
