### PR TITLE
Use stageout errors from WMCore

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by juztas** [comment]
Some discussions to follow up in the meeting today.

**Comment by juztas** [comment]
This adds 4 new exitCodes/msg which need to be add to WMCore:
```
89999 - Failure to parse (ROOT) job ad file or job report file for the job.
80003 - Fatal error uploading logs archive file metadata
80001 - Fatal error uploading output files metadata
80002 - Fatal error uploading input files metadata
```
With this pull request there should not be anymore Post-Processing failed, but correct error codes reported.

**Comment by belforte** [comment]
@juztas that's too much fine grained. I'd like to use exit code to classify broad failures which sort of require common action, and leave it to log for details. Can we do with  a single exit code for "failed to upload meatadata to CouchDB"  ? This is hopefully rare enough that we do not need to keep statistics depending on which exact file of metadata it was trying to upload.

**Comment by juztas** [comment]
not to couch, to crabserver. I will change to one exit code

**Pull request merged**
