### PR TITLE
Adjust probe walltime to fit better into pilots.

### PR DESCRIPTION
**Pull request by matz-e**
Also add some stubs to take care of tail jobs. Question from my side: will the walltime given to condor increase in case the testjob takes longer than 4*15 minutes to process a lumi-section?

@belforte priority for the probe job is already taken care of.

### CODE REVIEW

**Comment by belforte** [comment]
can you clarify the question ? who should increase what ?

**Comment by matz-e** [comment]
I'm wondering if there is some mechanism on the schedd that will increase the max walltime of the probe when retrying. Say that the probe will actually need 2h to process 1 lumi-section. Condor will kill it after 1h with the code in the PR. Will the probe get retried? Will the walltime for retries increase?

**Comment by belforte** [comment]
We'd have to do that in the postJob, which is anyhow the thing which triggers resubmissions. Currently jobs which exceed the request wall time are not retried.

**Comment by belforte** [comment]
let me be more clear. Job resubmission is always done in the postJob, never by condor. Condor restarts jobs which do not complete due to "incidents", but that's a different story. When condor kills the job because it reached RSS or T limits, it does not restart it. What happens next depends on the postJob.
Current postJob retries  after certain errors, but not after RSS or T limits have been hit.
So we can do whatever we want, but have to write the code :-)

**Comment by matz-e** [comment]
OK, thank you for clarifying!

**Pull request merged**
