### PR TITLE
Run condor_dagman in recovery mode. Fix resubmission of jobs. 

### PR DESCRIPTION
**Pull request by AndresTanasijczuk**
I would like @bbockelm to give his opinion about running condor_dagman in recovery mode even when a DAG rescue file is present (see dag_bootstrap_startup.sh). The reason I propose to run on recovery mode is because I couldn't find a way to have a well controlled resubmission of single jobs when condor_dagman runs in rescue mode.

### CODE REVIEW

**Comment by AndresTanasijczuk** [comment]
Fixes #4501, #4595.
Fixes #4683, but user has to take care of invalidating the publication of the successful job before resubmitting it. We don't do anything with respect to publication; we just resubmit the job.

**Comment by AndresTanasijczuk** [comment]
Added: Don't hard-code the number of automatic job retries. Instead read it from the TW config and add it to the job ad. If not specified in the TW config, use default of 2.

**Comment by mmascher** [comment]
Hi Andres, can you rebase this please ?

**Comment by bbockelm** [comment]
Starting to look through this.  A few thoughts:
* This patch is quite difficult to review.  A lot of the changes are trivial variable renames, whitespace changes, changes in capitalization.  That sort of stuff should be done as a separate commit.
* The concept of always using recovery is fine - in fact, it's probably correct.  You are right in that doing a "crab kill" followed by "crab resubmit -i 1,2,3,4" would cause a resubmit of all unfinished jobs right now.  Further, in the current setup, if there's a bug and "crab kill" does not kill all running jobs (we've seen this before!), then "crab resubmit" in rescue mode won't notice the existing jobs.  Potentially, you can have two jobs running after a "crab kill" in the existence of a bug -- not good!
* You seem to rework how resubmit parameters are passed along.  I don't have the ability to review these right now.  Can you propose a testing protocol that someone like @juztas could follow to validate this patch?  Certainly, we have to do a lot of "crab kill" + "crab resubmit" variations...

**Comment by belforte** [comment]
would it make sense to always assume that "crab kill" can fail
and build resilience in the design ? rather then trying to catch
problems by testing something that rarely fails ?

**Comment by bbockelm** [comment]
Hi Stefano,

That's precisely what Andres' change does and is one of the reasons I like it.

Brian

**Pull request merged**
