### PR TITLE
Fix WebUI to display Rucio URL to the rule

### PR DESCRIPTION
**Pull request by novicecpp**
Subtask of https://github.com/dmwm/CRABServer/issues/7797

Now you can click link in "Transfer Info" tab -> "ASO job" column, to go to Rucio Web UI to see the rule status.

Screenshot from 2023-08-08 15-29-22

### CODE REVIEW

**Comment by belforte** [comment]
Very nice. Thanks !
Only one suggestion:  change column header `ASO Job` to `FTS Job / Rucio Rule`

**Comment by belforte** [comment]
this should also fix https://github.com/dmwm/CRABServer/issues/7421

**Comment by novicecpp** [comment]
> Very nice. Thanks ! Only one suggestion: change column header `ASO Job` to `FTS Job / Rucio Rule`

Actually, I changed it to "ASO job" instead because it is a bit hard to change header of the table dynamically.

**Comment by belforte** [comment]
> Actually, I changed it to "ASO job" instead because it is a bit hard to change header of the table dynamically.

yes, I understand that. I was suggesting to put the both names to mean "it can be either or or the other".  Which one is used will be evident after clicking, unless one has the minimum experience to tell from "job" id format

**Comment by novicecpp** [comment]
Ah. I see. Will fix.

**Review by belforte — APPROVED** [review]

**Pull request merged**
