### PR TITLE
Memory and walltime warnings

### PR DESCRIPTION
**Pull request by juztas**
This pull request will not allow to submit/resubmit with walltime bigger then 2800, CRAB3 will change to 2800
Gives warning for submit/resubmit of memory bigger then 2500 and walltime bigger then 2800
It is one line add for shuffling good schedulers list and not using it static

### CODE REVIEW

**Comment by mmascher** [comment]
I thought we were going to do that on the client.
Also, I added an `uploadWarning` method to TaskAction (Not sure I already merged this though). We might want to use that.
And finally, no sites is giving more than two days of walltime, right?

**Comment by juztas** [comment]
in my opinion, maybe keep client light :)
Walltime see: https://github.com/dmwm/CRABServer/issues/4742 and some sites give, T2_CH_CERN gives 7 days

**Comment by belforte** [comment]
for site which let us run longer, we will run long pilots, but still limit user jobs to 2 days.
If, one day, there is a realistic use case where it is impossible to split a task to fit.. we'll look at it with great curiosity and interest.

**Comment by belforte** [comment]
I like to give warning in client, so that server can simply do the work w/o worrying about uploading messages. But in the end is an implementation decision.

**Comment by belforte** [comment]
English of the message text could be improved.
E.g.  "You have specified %s memory requirement and jobs can stay idle....."
becomes: "WARNING: request %s memory but only %s is guaranteed to be available. Jobs may not find a site where to run"
By the way, does crab status say "idle" or "submitted" for jobs waiting in schedd ?

**Comment by juztas** [comment]
I improved warning message ;)

Will show idle
```
Details:			idle          100.0% (1/1)
```

**Comment by belforte** [comment]
thanks @juztas so what about:
"WARNING: task requests %s memory but only %s is guaranteed to be available. Jobs may not find a site where to run and stay idle forever"
?

**Comment by belforte** [comment]
I am also confused by this line with "random.shuffle"
https://github.com/juztas/CRABServer/blob/reasonableMemory/src/python/TaskWorker/Actions/DagmanSubmitter.py#L165
I though it was  confirmed one/two days ago that schedd's are weighted by available RAM

**Comment by mmascher** [comment]
Argh, the `uploadWarnig` function I wasl talking about is not merged yet (*). I will push it now.

https://github.com/mmascher/CRABServer/commit/fc1fc4ef9b0c5793ca51609ad388625c3e381ce3#diff-e1b6cc982baa3dc006c12b8351f39b36R36

**Comment by juztas** [comment]
@belforte Which part was not clear? https://cms-logbook.cern.ch/elog/GlideInWMS/1837 
```Yes, this is still selection logic for first scheduler. If TW fails to submit to that scheduler, it tries to all other left schedulers which
are in the rest configuration from 1 till N in the list, except which was selected by CS.
```
It was first implementation of late binding and we are improving. For selection weighted by available memory, it has to be implemented in HTCondorLocator to exclude already tried schedulers.

**Comment by juztas** [comment]
@mmascher I will have to change ?:/

**Comment by mmascher** [comment]
Yes please, I merged it now. Use the `uploadWarning` function (available with self.uploadWarning), the code is more readable and if we decide to change somethign the way we upload warnings it will be easier.

**Comment by juztas** [comment]
Changed. And I have removed `shuffle` and will change this with blacklisting tried schedulers in HTCondorLocator

**Comment by bbockelm** [comment]
@juztas - I think you want to shuffle all schedds except for the one picked by TW?

This way, if the submit for the expected schedd goes poorly, we don't have all tasks submitted to the same schedd.

It's a good principle that we always want some non-deterministic behavior in ordering to avoid "clumping" to schedds.

**Comment by belforte** [comment]
@bbockelm doesn't HTCondorLocator already have an element of randomness ?
https://github.com/dmwm/CRABServer/blob/master/src/python/HTCondorLocator.py#L11

**Comment by bbockelm** [comment]
If I'm reading the code right, we:

1. Get the list of good schedds from cmsweb.  This appears to be a statically-ordered list.
2. Insert the primary schedd (as chosen at task submit) to the front of the list.

I think we should add a step "1a", where we shuffle the list from cmsweb.

**Comment by juztas** [comment]
yes, 1a was added before

**Pull request merged**
