### PR TITLE
Fix getNativeRucioClientload load wrong config

### PR DESCRIPTION
**Pull request by novicecpp**
Fix https://github.com/dmwm/CRABServer/pull/8006

Fix the `getNativeRucioClient()` to load correct config. Also change PreDag.py to assign user cert path to proper config attribute.

### CODE REVIEW

**Comment by belforte** [comment]
even if not now. It will be good to record a minimal explanation with this PR
Do IUC that in the code we had not switched to pick Rucio credential from the new `Services` section of the config ? :-(

**Comment by novicecpp** [comment]
In short, yes. 
I will add everything later.

**Comment by belforte** [comment]
no hurry. thanks for sorting this out.

**Review by belforte — APPROVED** [review]

**Comment by belforte** [comment]
good. Thanks

**Pull request merged**
