### PR TITLE
Fix all possibly unbound in DBSDataDiscovery

### PR DESCRIPTION
**Pull request by novicecpp**
Fix https://github.com/dmwm/CRABServer/issues/8100 and potential bugs that may cause `local variable referenced before assignment`. The "potential bugs" are reported by pyright as explained in https://github.com/dmwm/CRABServer/issues/8100#issuecomment-1857383835.

### CODE REVIEW

**Comment by novicecpp** [comment]
Task with [HC dataset](https://cmsweb-test12.cern.ch/crabserver/ui/task/231215_070437%3Atseethon_crab_hc_1kj_test12_20231215_080432) and [User dataset](https://cmsweb-test12.cern.ch/crabserver/ui/task/231215_070503%3Atseethon_crab_user_dataset_user_test12_20231215_080500) is submitted properly.

**Review by belforte — APPROVED** [review]

**Comment by belforte** [comment]
perfect, thanks. And sorry for the bug.

**Comment by belforte** [comment]
you can merge

**Comment by novicecpp** [comment]
Thanks.

**Pull request merged**
