### PR TITLE
add SUBMITREFUSED to task statuses to monitor. Fix #8620

### LINKED ISSUE #8620: make the new SUBMITREFUSED status visible in Grafana

### PR DESCRIPTION
**Pull request by belforte**
I verified that this change adds the info to the json doc and does not break the code.
I think we need to merge and deploy on crab-prod-tw02 to see if data appears in OpenSeach and add a query to grafana panel
I guess I can kick off a gitlab pipeline to test this from my local repo ? What do you think @mapellidario ?
But there's no way to deploy it on prod2, via gitlab, right ?

### CODE REVIEW

**Comment by belforte** [comment]
OK. I am using pipeline to build w/o deploy. Then can give it a try on prod2. Nothing bad will happen, at worst some odd value in our grafana.

**Comment by mapellidario** [comment]
So, i have added some information to [1].

I suggest that 

- [ ] you build the new container, 
- [ ] then i change the version of the monit container running in crab-dev-tw02 [2], 
- [ ] we let it run for a while 
- [ ] and we check the result from the grafana dashboard that reads from the test opensearch index (which is called `monit_crab_test` inside grafana) [3]

the link at [3] default at the crab-dev-tw01, where i think that you Stefano run your tests. we can change the monit source to crab-dev-tw02 to check how it goes over night

---

[1] https://cmscrab.docs.cern.ch/technical/crab-monitoring/crab-crontabs.html
[2] https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/847146c82b69e4af6fef67ffd8694a917c17acb6/data/fqdns/crab-dev-tw02.cern.ch.yaml#L19
[3] https://monit-grafana.cern.ch/goto/hUZgBFjIR?orgId=11

**Comment by belforte** [comment]
I would deploy straight on prod02 and see how it goes.
Anyhow image is there now
registry.cern.ch/cmscrab/crabtaskworker:pypi-test2-add-submitrefused-4.monit

**Comment by belforte** [comment]
I will not touch crab-prod-tw02 tonight

**Review by mapellidario — APPROVED** [review]
changes look good to me and i saw some "submitrefused" tasks in the test grafana dashboard (link provided in a previous comment).
thanks stefano, i think this PR is ready to be merged

**Comment by belforte** [comment]
here we go with a Ferragosto-merge

**Pull request merged**
