### PR TITLE
beware extra spaces in accelerator_jdl too

### PR DESCRIPTION
**Pull request by belforte**

### CODE REVIEW

**Comment by novicecpp** [comment]
Do we really need this PR? Because `accelerator_jdl` is constructed by `DagmanCreator.py`

https://github.com/dmwm/CRABServer/blob/886a75271ac769a56ef7eb1bf016d649b3c4ff3a/src/python/TaskWorker/Actions/DagmanCreator.py#L507-L522

**Comment by belforte** [comment]
then we do not need it. My apologies for not having looked up where that is created.

**Comment by novicecpp** [comment]
No need to apologize and sorry for using strong word.
I was wondering if you seen something that it didn't see here :-)

**Comment by belforte** [comment]
which strong word ?
Anyhow  we do not need the effort to revert this, that code will anyhow change with #8336

**Pull request merged**
