### PR TITLE
Allow use different cert for rucio client

### PR DESCRIPTION
**Pull request by novicecpp**
By specify `config.Services.Rucio_cert` and `config.Services.Rucio_key` in [TaskWorkerConfig.py](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/master/code/templates/crabtaskworker/taskworker/TaskWorkerConfig.py.erb)

### CODE REVIEW

**Comment by belforte** [comment]
I am curious, what is the use case for needing a different cert for Rucio client and TW other work like talking with REST (I guess) ?

**Review by belforte — APPROVED** [review]

**Comment by belforte** [comment]
@novicecpp what do we do with this ? if it is useful, I have no problems, but if not, let's keep code "simpler"

**Comment by novicecpp** [comment]
Yes, it is still useful to me. But keep it for a week before merging into master. I need to look into puppet code which may have a simpler way to do it.

**Comment by novicecpp** [comment]
I am merging this. Still looking for better solution.

**Pull request merged**
